# Fundamentos de SQL para análisis

In [ ]:
# @title Postgress preloading (install server)
#The output of the installation is not displayed when %%capture is used at the start of the cell
%%capture
# Install postgresql server
!pip install ipython-sql

!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo service postgresql start

# Setup a password `postgres` for username `postgres`
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"
# Setup a database with name `sampledb` to be used
# !sudo -u postgres psql -U postgres -c 'DROP DATABASE IF EXISTS sampledb;'
# !sudo -u postgres psql -U postgres -c 'CREATE DATABASE sampledb;'

!curl https://raw.githubusercontent.com/limspiga/data-modeling-fall-24/main/db/data.dump  -O
!sudo -u postgres psql -U postgres -c 'CREATE DATABASE sqlda;'

# !sudo -u postgres psql -U postgres -d 'sqlda' -f 'data.dump'

# https://thivyapriyaa.medium.com/setting-up-postgresql-on-google-colab-4d02166939fc

In [ ]:
# @title Postgress preloading
# import
!sudo -u postgres psql -d sqlda < data.dump
%env DATABASE_URL=postgresql://postgres:postgres@localhost:5432/sqlda
#To load the sql extention to start using %%sql
%load_ext sql

#1.1 Introducción

La transformación en la forma en que las empresas y organizaciones almacenan y gestionan sus datos ha sido significativa.

1. Dos herramientas clave en este cambio son
  - las bases de datos relacionales y
  - el Lenguaje de Consulta Estructurado (SQL).

  Estas tecnologías desempeñan un papel fundamental en el procesamiento de grandes volúmenes de información, esenciales para las empresas que manejan datos masivos.

Las bases de datos relacionales se han convertido en el principal medio de almacenamiento de datos. Una parte considerable de esta información se transfiere a almacenes de datos especializados para análisis avanzados, los cuales, en su mayoría, son accesibles a través de SQL.

Las bases de datos **NoSQL** surgieron como una alternativa a las relacionales, ofreciendo flexibilidad para manejar datos no estructurados y realizar operaciones distribuidas de lectura/escritura. Aunque no siguen el formato relacional ni utilizan SQL, están diseñadas para tareas específicas que las bases de datos relacionales no gestionan de manera eficiente. Sin embargo, NoSQL no es una solución universal, sino un complemento a las bases relacionales, que siguen siendo fundamentales en la gestión de datos.

Las bases de datos relacionales son versátiles, ofreciendo un equilibrio entre características y rendimiento.
- Utilizan SQL, un lenguaje con bases matemáticas y fácil de aprender, lo que las convierte en una excelente opción para quienes se inician en el análisis de datos.

Aunque algunas tareas específicas pueden requerir bases de datos NoSQL, SQL sigue siendo una herramienta fundamental para el análisis de datos.

**Bases de Datos Relacionales vs NoSQL**

- **Bases de Datos Relacionales**
  - Características:
    - Requieren formato específico.
    - Usan un algoritmo particular para procesamiento.
  - Ventajas:
    - Versátiles: buen balance entre características y rendimiento.
    - Universalidad: todas utilizan SQL.
    - Fundamentos sólidos: SQL tiene una base matemática robusta.
    - Facilidad de aprendizaje: SQL es intuitivo para muchos principiantes.
  - Aplicación:
    - Punto de partida ideal para análisis de datos.
    - Cubre la mayoría de las necesidades de las personas.

- **Bases de Datos NoSQL**
  - Origen:
    - Creadas como alternativa al formato relacional y SQL.
  - Características:
    - Capaces de trabajar con datos no estructurados (ej. tweets).
    - Realizan operaciones distribuidas.
  - Terminología:
    - Evolución del término: De "NoSQL" a "Not Only SQL".
  - Limitaciones:
    - Más orientadas a necesidades específicas.
    - No son una solución universal.
  - Aplicación:
    - Añadido en el mundo de gestión de datos, no un sustituto.


# 1.2 El Mundo de los Datos

Los datos se pueden dividir en tres categorías principales:
- estructurados,
- semi-estructurados y
- no estructurados.



<figure>
<center><img src='https://github.com/limspiga/data-modeling/blob/main/images/67733acf-d83a-4c54-902a-760467625c72.png?raw=true' width="400" />
<figcaption>Figura 2.1: La clasificación de los tipos de datos</figcaption></center>
</figure>

<center>

| Tipo de Datos          | Definición y Características                                                                                  | Ejemplo                                                         |
|------------------------|---------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------|
| **Datos Estructurados**| - Definición atómica clara. <br> - Tipo, rango y significado de valores definidos. <br> - Orden estricto.     | Tarjeta de inscripción escolar: <br> - Número de identificación. <br> - Nombre. <br> - Fecha de nacimiento.              |
| **Datos No Estructurados** | - Sin definición clara. <br> - Difícil extracción y análisis.                                                | - Bloque binario: <br>   * Archivos de video. <br>   * Archivos de audio. <br> - Tokens naturales: <br>   * Redes sociales. <br>   * Discursos humanos.   |
| **Datos Semi-estructurados** | - Sin formato y significado predefinidos. <br> - Cada valor está etiquetado con su definición.             | Información de una casa: <br> - Dirección. <br> - Sótano (opcional). <br> - Garaje (opcional). <br> - Mejoras futuras.    |

</center>

# 1.3 Bases de Datos Relacionales y SQL
Una base de datos relacional usa un modelo relacional, organizando los datos en relaciones o conjuntos de tuplas. Una tupla, también conocida como registro, es una serie ordenada de atributos que describen dicho registro.

Por ejemplo, una empresa de bienes de consumo de rápido movimiento quiere rastrear a sus clientes. Pueden guardar la información del cliente en una relación llamada customer_info (información del cliente). Cada registro en esta relación contiene detalles sobre un cliente. Los atributos en cada registro incluyen información como el apellido del cliente, nombre, edad, fecha de inscripción y dirección de entrega. Esta relación y sus dos primeros registros se verían así:

<center>

| ID | Last Name | First Name | Age |
|---|---|---|---|
| 1 | Smith | John | 27 |
| 2 | Higgins | Mary | 53 |

Figure 2.2: Ejemplo de customer_info relation

</center>

Como puede ver, cada relación es efectivamente una tabla bidimensional que se parece a una hoja de cálculo de Excel. Por lo tanto, cuando se implementa en una base de datos relacional, estas relaciones se llaman tablas. Cada tabla está compuesta por filas y columnas. Cada fila de la tabla es un registro, y los atributos se representan como columnas de la tabla. No puede haber columnas duplicadas y las columnas deben seguir el mismo orden en todas las filas. Cada columna también tiene un tipo de datos que describe el tipo de datos en la columna.

Aunque no es técnicamente necesario, la mayoría de las tablas en una base de datos relacional tienen una columna (a veces un grupo de columnas) denominada clave primaria, que identifica de manera única una fila de la base de datos. En el ejemplo mostrado en la Figura 2.2, cada fila contiene una columna llamada ID. Este registro, como sugiere el nombre, es un atributo que se puede usar para identificar de manera única este registro. Se conoce como clave relacional. En todas las demás columnas, puede tener datos duplicados en diferentes filas. Pero en la(s) columna(s) de clave primaria, los datos deben ser únicos.

**Base de Datos Relacional y Operaciones CRUD**

- **Base de datos relacional**:
  - Organizadas alrededor de tablas.
  - Datos almacenados dentro de las tablas.

- **Operaciones en Bases de Datos**:
  - **CRUD**:
    - **C** - Crear:
      - Definir el conjunto de datos.
      - Crear registros de datos individuales y colocarlos en el conjunto.
    - **R** - Leer:
      - Acceder y visualizar toda la información del conjunto de datos.
    - **U** - Actualizar:
      - Modificar los registros afectados por cambios.
    - **D** - Eliminar:
      - Eliminar registros individuales.
      - Si no es necesario el conjunto, eliminar toda la definición del conjunto en la base de datos.

- **Objetivo de eliminar registros**:
  - Ahorrar costos de almacenamiento.
  - Aumentar rendimiento.

**Nota**: CRUD es el acrónimo de Crear, Leer, Actualizar y Eliminar.



## 1.3.1 Ventajas y Desventajas de las Bases de Datos SQL
**Resumen:**
Las bases de datos relacionales (SQL) son herramientas ampliamente utilizadas para almacenar y procesar datos estructurados debido a sus múltiples ventajas, tales como la representación intuitiva, eficiencia en almacenamiento, declaratividad y robustez. Sin embargo, enfrentan desafíos en áreas como la escalabilidad, el procesamiento de datos no estructurados y el equilibrio entre consistencia y rendimiento.

**Comparativa: Ventajas vs. Desventajas**

**Ventajas:**
1. **Intuitivo:** Representación clara y fácil de entender con tablas.
2. **Eficiente:** Normalización evita redundancia de datos, optimizando el espacio.
3. **Declarativo:** SQL especifica qué datos se quieren sin preocuparse por cómo obtenerlos.
4. **Robusto:** Cumplimiento de atomicidad, consistencia, aislamiento y durabilidad (ACID) garantiza la validez de los datos.

**Desventajas:**
1. **Especificidad relativamente baja:** Limitaciones en la funcionalidad preprogramada.
2. **Escalabilidad limitada:** El costo de recursos crece exponencialmente con la información.
3. **Sacrificar rendimiento por consistencia:** Mecanismos complejos pueden disminuir el rendimiento en escenarios que no requieren alta consistencia.
4. **Falta de capacidad para procesar datos semi-estructurados y no estructurados:** Las bases de datos SQL se centran principalmente en datos estructurados, lo que limita su versatilidad con otros tipos de datos.

# 1.4 Postgres Sistema de Gestión de Bases de Datos Relacionales (RDBMS)
Postgres es un RDBMS que administra datos en sistemas informáticos, asegurando su adecuado almacenamiento y recuperación mediante el lenguaje SQL.

Los RDBMS, que manejan bases de datos, vienen en dos variedades: comerciales y de código abierto. Aunque todos siguen en su mayoría un estándar de SQL establecido por ANSI, cada uno tiene pequeñas diferencias en su funcionamiento y en el uso del lenguaje SQL. Durante este curso, usaremos Colab como nuestra herramienta principal para trabajar con SQL. Colab actúa como un espacio de almacenamiento temporal para los datos, y los usuarios interactúan con él a través de distintas herramientas cliente.

A continuación, se presenta la lista de tablas contenidas en la base de datos SQLQA, acompañada de una breve descripción de cada una:

| **Nombre de la tabla**                   | **Descripción**                                                                                                                                                         |
|-----------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| closest_dealerships                     | Contiene la distancia entre cada cliente y concesionario                                                                                                               |
| countries                               | Una tabla vacía con columnas que describen países                                                                                                                      |
| customer_sales                          | Contiene datos brutos en un formato semi-estructurado de algunos registros de ventas                                                                                    |
| customer_survey                         | Contiene retroalimentación con calificaciones de los clientes                                                                                                          |
| customers                               | Contiene información detallada para todos los clientes                                                                                                                 |
| dealerships                             | Contiene información detallada para todos los concesionarios                                                                                                           |
| emails                                  | Contiene los detalles de los correos electrónicos enviados a cada cliente                                                                                              |
| products                                | Contiene los productos vendidos por ZoomZoom                                                                                                                           |
| public_transportation_by_zip            | Contiene la medida de disponibilidad de transporte público en diferentes códigos postales en Estados Unidos                                                            |
| sales                                   | Contiene los registros de ventas de ZoomZoom basados en un registro por cliente por producto                                                                           |
| salespeople                             | Contiene los detalles de los vendedores en todos los concesionarios                                                                                                     |
| top_cities_data                         | Contiene algunos datos agregados sobre el número de clientes en diferentes ciudades                                                                                     |


## Ejercicio 2.01: Realizando tu primera consulta con SELECT.
En este ejercicio, emplearás Python para establecer una conexión con una base de datos de muestra denominada ZoomZoom en tu servidor postgres y llevarás a cabo una consulta SQL sencilla.

1. Descarga la base de datos sqlda

In [ ]:
# !pip install tabulate
# import sqlite3
# from tabulate import tabulate

# # Descargamos la base de datos sqlda
# !curl https://raw.githubusercontent.com/limspiga/data-modeling/main/db/sqlda.sql -O

2. La base de datos sqlda.sql contiene datos de muestra de una empresa imaginaria llamada ZoomZoom, dedicada a la venta en línea de automóviles y scooters eléctricos a través de su plataforma web y red de concesionarios. En cada concesionario hay un vendedor encargado. Los clientes, tras realizar una compra, pueden optar por completar una encuesta. Adicionalmente, ZoomZoom envía correos electrónicos promocionales a sus clientes, registrando las fechas de envío, apertura, clics y el contenido del mensaje.

  Ahora, introduce la consulta siguiente en el terminal:

In [ ]:
%%sql
  SELECT first_name
  FROM customers
  WHERE state='AZ'
  ORDER BY first_name LIMIT 2;

2 rows affected.


[('Abba',), ('Abbey',)]

 El resultado de este SQL aparece debajo del editor de consultas.

La consulta SQL que acabas de ejecutar en este ejercicio es una sentencia SELECT.


## 1.4.1 Declaración SELECT
En una base de datos relacional, las operaciones CRUD se ejecutan mediante declaraciones SQL. Una declaración SQL es un comando que utiliza ciertas palabras clave de SQL y sigue ciertos estándares para especificar qué resultado esperas de la base de datos relacional. En el Ejercicio 2.01, Ejecutando tu primera consulta SELECT, viste un ejemplo de declaración SQL SELECT. SELECT es probablemente la declaración SQL más común; recupera datos de una base de datos. Esta operación se realiza casi exclusivamente usando la palabra clave SELECT.

La consulta SELECT más básica sigue este patrón:

```
# SELECT...FROM <nombre_tabla>;
```
Esta consulta es una forma de extraer datos de una única tabla. En su forma más simple, si quieres extraer todos los datos de la tabla de productos en la base de datos de muestra, simplemente usa esta consulta:

In [ ]:
%%sql
  SELECT * FROM products;

 * postgresql://postgres:***@localhost:5432/sqlda
12 rows affected.


[(1, 'Lemon', 2013, 'scooter', Decimal('399.99'), datetime.datetime(2012, 10, 28, 0, 0), datetime.datetime(2015, 2, 3, 0, 0)),
 (2, 'Lemon Limited Edition', 2014, 'scooter', Decimal('799.99'), datetime.datetime(2013, 8, 30, 0, 0), datetime.datetime(2013, 11, 24, 0, 0)),
 (3, 'Lemon', 2016, 'scooter', Decimal('499.99'), datetime.datetime(2015, 12, 27, 0, 0), datetime.datetime(2021, 8, 24, 0, 0)),
 (5, 'Blade', 2017, 'scooter', Decimal('699.99'), datetime.datetime(2017, 2, 17, 0, 0), datetime.datetime(2017, 9, 23, 0, 0)),
 (7, 'Bat', 2019, 'scooter', Decimal('599.99'), datetime.datetime(2019, 6, 7, 0, 0), None),
 (8, 'Bat Limited Edition', 2020, 'scooter', Decimal('699.99'), datetime.datetime(2019, 10, 13, 0, 0), None),
 (12, 'Lemon Zester', 2022, 'scooter', Decimal('349.99'), datetime.datetime(2021, 10, 1, 0, 0), None),
 (4, 'Model Chi', 2017, 'automobile', Decimal('115000.00'), datetime.datetime(2017, 2, 17, 0, 0), datetime.datetime(2021, 8, 24, 0, 0)),
 (6, 'Model Sigma', 2018, 'automobile', Decimal('65500.00'), datetime.datetime(2017, 12, 10, 0, 0), datetime.datetime(2021, 5, 28, 0, 0)),
 (9, 'Model Epsilon', 2020, 'automobile', Decimal('35000.00'), datetime.datetime(2019, 10, 13, 0, 0), None),
 (10, 'Model Gamma', 2020, 'automobile', Decimal('85750.00'), datetime.datetime(2019, 10, 13, 0, 0), None),
 (11, 'Model Chi', 2022, 'automobile', Decimal('95000.00'), datetime.datetime(2021, 10, 1, 0, 0), None)]


Esta consulta extraerá todos los datos de una base de datos. La salida será:


<figure>
<center><img src='https://github.com/limspiga/data-modeling/blob/main/images/4e5bfa84-8e92-4d9d-99ed-35217e5e84d9.png?raw=true' width="600" />
<figcaption>Figure 2.7: Simple SELECT statement</figcaption></center>
</figure>

Es importante entender la sintaxis de la consulta SELECT con un poco más de detalle.

Nota

En las declaraciones presentadas en esta sección, las palabras clave de SQL, como SELECT y FROM, están en letras mayúsculas, mientras que los nombres de tablas y columnas se muestran en minúsculas. Aunque SQL no diferencia entre mayúsculas y minúsculas en sus declaraciones y palabras clave, es recomendable seguir ciertas convenciones de formato y estructura al escribir. Esto facilita la comprensión de la estructura y finalidad de la declaración.

Dentro de la cláusula SELECT, el símbolo * sirve como abreviatura para seleccionar todas las columnas de una base de datos. Se utiliza el punto y coma (;) al final de la consulta para señalar su conclusión, similar a cómo un punto finaliza una oración. Si deseas seleccionar columnas específicas en una consulta, simplemente sustituye el asterisco (*) por los nombres de las columnas deseadas en el orden en que prefieras que se muestren. Por ejemplo, para mostrar las columnas product_id y model de la tabla products, la consulta sería:

In [ ]:
# conn = sqlite3.connect('sqlda.sql')
# cur = conn.cursor()

# cur.execute('SELECT product_id, model FROM products;')

# # Fetch column names
# headers = [column[0] for column in cur.description]
# print(tabulate(cur,  headers=headers))

# conn.close()

%%sql
  SELECT product_id, model FROM products;

 * postgresql://postgres:***@localhost:5432/sqlda
12 rows affected.


[(1, 'Lemon'),
 (2, 'Lemon Limited Edition'),
 (3, 'Lemon'),
 (5, 'Blade'),
 (7, 'Bat'),
 (8, 'Bat Limited Edition'),
 (12, 'Lemon Zester'),
 (4, 'Model Chi'),
 (6, 'Model Sigma'),
 (9, 'Model Epsilon'),
 (10, 'Model Gamma'),
 (11, 'Model Chi')]

La respuesta se mostrará de la siguiente manera:

<figure>
<center><img src='https://github.com/limspiga/data-modeling/blob/main/images/71d622a3-2af1-4f0d-9e59-345e9fb5866b.png?raw=true' width="200" />
<figcaption>Figure 2.7: Simple SELECT statement</figcaption></center>
</figure>

Figura 2.8: Sentencia SELECT con nombres de columnas
Para mostrar primero la columna model y luego la columna product_id, escribirías lo siguiente:


In [ ]:
# conn = sqlite3.connect('sqlda.sql')
# cur = conn.cursor()

# cur.execute('SELECT model, product_id FROM products;')

# # Fetch column names
# headers = [column[0] for column in cur.description]
# print(tabulate(cur,  headers=headers))

# conn.close()

%%sql
  SELECT model, product_id FROM products;

 * postgresql://postgres:***@localhost:5432/sqlda
12 rows affected.


[('Lemon', 1),
 ('Lemon Limited Edition', 2),
 ('Lemon', 3),
 ('Blade', 5),
 ('Bat', 7),
 ('Bat Limited Edition', 8),
 ('Lemon Zester', 12),
 ('Model Chi', 4),
 ('Model Sigma', 6),
 ('Model Epsilon', 9),
 ('Model Gamma', 10),
 ('Model Chi', 11)]


La respuesta se mostrará de la siguiente manera:

<figure>
<center><img src='https://github.com/limspiga/data-modeling/blob/main/images/2914d3b5-fc04-480f-8b1d-15df7d13e0da.png?raw=true' width="200" />
<figcaption>Figura 2.9: Comparación entre las sentencias SELECT con nombres de columnas de las Figuras 2.8 y 2.9.</figcaption></center>
</figure>

Es esencial entender que, a pesar de que las columnas se muestran en el orden establecido en la consulta `SELECT`, las filas se presentarán de manera no secuencial.

Una consulta SELECT se estructura en cinco segmentos:
1. **Operación**: Se refiere a lo que se mostrará. Por ejemplo, el término SELECT seguido de los nombres de las columnas o funciones.
2. **Datos**: Representado por la palabra clave `FROM`, seguida de las tablas relacionadas, especifica qué información será considerada para acciones como filtrado y cálculos.
3. **Condición**: Es el segmento que limita los datos, mostrando únicamente aquellos registros que cumplan con ciertas condiciones, generalmente marcadas con `WHERE`.
4. **Agrupación**: Envolucra la reunión de registros basándose en criterios determinados por una cláusula `GROUP BY`, generando salidas basadas en valores similares. Profundizarás en este aspecto en el Capítulo 4, Funciones Agregadas para el Análisis de Datos.
5. **Postprocesamiento**: Es el proceso final que ajusta y organiza los resultados, comúnmente usando términos como `ORDER BY` y `LIMIT`.

Como ilustración, toma en cuenta la declaración que realizaste en el Ejercicio 2.01, donde quisieras obtener el nombre principal de todos los clientes en Arizona, listados alfabéticamente. La consulta `SELECT` para este propósito sería:



In [ ]:
%%sql
  SELECT first_name
  FROM customers
  WHERE state='AZ'
  ORDER BY first_name LIMIT 10;

 * postgresql://postgres:***@localhost:5432/sqlda
10 rows affected.


[('Abba',),
 ('Abbey',),
 ('Abra',),
 ('Abrahan',),
 ('Adams',),
 ('Adham',),
 ('Adora',),
 ('Adore',),
 ('Adrianna',),
 ('Agnese',)]

Los resultados iniciales se visualizan de la siguiente manera:

<figure>
<center><img src='https://github.com/limspiga/data-modeling/blob/main/images/640a3027-ff64-4cc0-b1f7-0c2764ba4a97.png?raw=true' width="100" />
<figcaption>Figure 2.10: Sample SELECT statement.</figcaption></center>
</figure>

## 1.4.2 La Cláusula WHERE

La cláusula WHERE es una lógica condicional que limita la cantidad de datos devueltos. Puedes usar la cláusula WHERE para especificar condiciones basadas en las cuales la declaración SELECT recuperará filas específicas. En una declaración SELECT, generalmente encontrarás esta cláusula colocada después de la cláusula FROM.

La condición en la cláusula WHERE generalmente es una declaración booleana que puede ser verdadera o falsa para cada fila. En el caso de las columnas numéricas, estas declaraciones booleanas pueden usar operadores como igual (=), mayor que (>), o menor que (<) para comparar las columnas contra un valor.

Por ejemplo, supongamos que quieres ver los nombres de los modelos de los productos con el año modelo 2014 del conjunto de datos de muestra. Escribirías la siguiente consulta:

La salida de este SQL es:

In [ ]:
%%sql
  SELECT model
  FROM products
  WHERE year=2014 LIMIT 10;

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[('Lemon Limited Edition',)]

Figura 2.11: Cláusula WHERE simple

Mediante la cláusula WHERE, has logrado filtrar los productos según un criterio específico. Si estás interesado en productos anteriores al año 2014, simplemente ajusta la cláusula `WHERE a year < 2014`. Ahora, si deseas aplicar varios criterios simultáneamente o seleccionar filas que cumplan alguna de varias condiciones, puedes incorporar las cláusulas AND u OR en tus consultas.

## 1.4.3  La Cláusula AND/OR

La consulta previa, representada en la Figura 2.11, se basó en una única condición. No obstante, en ocasiones, podrías querer satisfacer múltiples criterios simultáneamente. Para lograrlo, puedes integrar distintas condiciones utilizando las cláusulas AND y OR. Mientras que AND selecciona las filas que cumplen con todas las condiciones establecidas, OR recoge aquellas que satisfacen al menos una de las condiciones especificadas.

Por ejemplo, si quieres obtener modelos que no solo fueron fabricados en 2014, sino que también tienen un Precio Sugerido por el Fabricante (MSRP) de menos de $1,000, puedes escribir la siguiente consulta:


In [ ]:
%%sql
  SELECT model, year, base_msrp
  FROM products
  WHERE year=2014
  AND base_msrp<=1000;

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[('Lemon Limited Edition', 2014, Decimal('799.99'))]


El resultado se verá así:
Figura 2.12: Cláusula WHERE con operador AND

Aquí, puedes ver que el año del producto es 2014 y el base_msrp es menor a $1,000. Esto es exactamente lo que estás buscando.

Supongamos que quieres obtener cualquier modelo que se lanzó en el año 2014 o que tenía un tipo de producto como automóvil. Escribirías la siguiente consulta:


In [ ]:
%%sql
  SELECT Model, product_type
  FROM products
  WHERE year=2014
  OR product_type='automobile';

 * postgresql://postgres:***@localhost:5432/sqlda
6 rows affected.


[('Lemon Limited Edition', 'scooter'),
 ('Model Chi', 'automobile'),
 ('Model Sigma', 'automobile'),
 ('Model Epsilon', 'automobile'),
 ('Model Gamma', 'automobile'),
 ('Model Chi', 'automobile')]





El resultado es el siguiente:
Figura 2.13: Cláusula WHERE con operador OR

Ya sabes que hay un producto, Lemon Limited Edition, del año 2014. El resto de los productos en el ejemplo están listados con "automobile" como product_type. Estás viendo el conjunto de datos combinado de year=2014 junto con product_type='automobile'. Eso es exactamente lo que hace el operador OR.

Al usar más de una condición AND u OR, es posible que necesites usar paréntesis para separar y posicionar las piezas de lógica juntas. Esto garantizará que tu consulta funcione como se espera y sea lo más legible posible. Por ejemplo, si quisieras obtener todos los productos con modelos entre los años 2016 y 2018, así como cualquier producto que sean scooters, podrías escribir lo siguiente:



In [ ]:
%%sql
  SELECT *
  FROM products
  WHERE year > 2016
  AND year < 2018
  OR product_type='scooter';

 * postgresql://postgres:***@localhost:5432/sqlda
8 rows affected.


[(1, 'Lemon', 2013, 'scooter', Decimal('399.99'), datetime.datetime(2012, 10, 28, 0, 0), datetime.datetime(2015, 2, 3, 0, 0)),
 (2, 'Lemon Limited Edition', 2014, 'scooter', Decimal('799.99'), datetime.datetime(2013, 8, 30, 0, 0), datetime.datetime(2013, 11, 24, 0, 0)),
 (3, 'Lemon', 2016, 'scooter', Decimal('499.99'), datetime.datetime(2015, 12, 27, 0, 0), datetime.datetime(2021, 8, 24, 0, 0)),
 (5, 'Blade', 2017, 'scooter', Decimal('699.99'), datetime.datetime(2017, 2, 17, 0, 0), datetime.datetime(2017, 9, 23, 0, 0)),
 (7, 'Bat', 2019, 'scooter', Decimal('599.99'), datetime.datetime(2019, 6, 7, 0, 0), None),
 (8, 'Bat Limited Edition', 2020, 'scooter', Decimal('699.99'), datetime.datetime(2019, 10, 13, 0, 0), None),
 (12, 'Lemon Zester', 2022, 'scooter', Decimal('349.99'), datetime.datetime(2021, 10, 1, 0, 0), None),
 (4, 'Model Chi', 2017, 'automobile', Decimal('115000.00'), datetime.datetime(2017, 2, 17, 0, 0), datetime.datetime(2021, 8, 24, 0, 0))]


El resultado contiene todos los scooters, así como un automóvil que tiene un año entre 2016 y 2018.
Figura 2.14: Cláusula WHERE con múltiples operadores AND/OR

Sin embargo, para aclarar la cláusula WHERE, sería preferible escribir lo siguiente:

In [ ]:
%%sql
  SELECT *
  FROM products
  WHERE (year>2016 AND year<2018)
  OR product_type='scooter';

 * postgresql://postgres:***@localhost:5432/sqlda
8 rows affected.


[(1, 'Lemon', 2013, 'scooter', Decimal('399.99'), datetime.datetime(2012, 10, 28, 0, 0), datetime.datetime(2015, 2, 3, 0, 0)),
 (2, 'Lemon Limited Edition', 2014, 'scooter', Decimal('799.99'), datetime.datetime(2013, 8, 30, 0, 0), datetime.datetime(2013, 11, 24, 0, 0)),
 (3, 'Lemon', 2016, 'scooter', Decimal('499.99'), datetime.datetime(2015, 12, 27, 0, 0), datetime.datetime(2021, 8, 24, 0, 0)),
 (5, 'Blade', 2017, 'scooter', Decimal('699.99'), datetime.datetime(2017, 2, 17, 0, 0), datetime.datetime(2017, 9, 23, 0, 0)),
 (7, 'Bat', 2019, 'scooter', Decimal('599.99'), datetime.datetime(2019, 6, 7, 0, 0), None),
 (8, 'Bat Limited Edition', 2020, 'scooter', Decimal('699.99'), datetime.datetime(2019, 10, 13, 0, 0), None),
 (12, 'Lemon Zester', 2022, 'scooter', Decimal('349.99'), datetime.datetime(2021, 10, 1, 0, 0), None),
 (4, 'Model Chi', 2017, 'automobile', Decimal('115000.00'), datetime.datetime(2017, 2, 17, 0, 0), datetime.datetime(2021, 8, 24, 0, 0))]

Recibirás el mismo resultado que antes. La lógica de este SQL es más fácil de entender. Descubrirás que las cláusulas AND y OR se utilizan con frecuencia en las consultas SQL. Sin embargo, en algunos escenarios, pueden resultar tediosas, especialmente cuando hay alternativas más eficientes para tales escenarios.

## 1.4.4  La Cláusula IN/NOT IN
Ahora que puedes escribir consultas que coincidan con múltiples condiciones, también podrías querer refinar tus criterios recuperando filas que contienen (o no contienen) uno o más valores específicos en una o más de sus columnas. Aquí es donde las cláusulas IN y NOT IN resultan útiles.

Por ejemplo, estás interesado en devolver todos los modelos de los años 2014,
2016 o 2019. Podrías escribir una consulta como esta:

In [ ]:
%%sql
SELECT model, year
FROM products
WHERE year = 2014
OR year = 2016
OR year = 2019;

 * postgresql://postgres:***@localhost:5432/sqlda
3 rows affected.


[('Lemon Limited Edition', 2014), ('Lemon', 2016), ('Bat', 2019)]

El resultado se verá como la siguiente imagen, mostrando tres modelos de estos tres años:

Sin embargo, esto es tedioso de escribir. Usando IN, puedes escribir lo siguiente:





In [ ]:
%%sql
SELECT model, year
FROM products
WHERE year IN (2014, 2016, 2019);

 * postgresql://postgres:***@localhost:5432/sqlda
3 rows affected.


[('Lemon Limited Edition', 2014), ('Lemon', 2016), ('Bat', 2019)]


Esto es mucho más limpio y facilita la comprensión de lo que está sucediendo. También
devolverá el mismo resultado que arriba.
Por el contrario, también puedes usar la cláusula NOT IN para devolver todos los valores que no están en una lista de valores. Por ejemplo, si quisieras todos los productos que no fueron producidos en los años 2014, 2016 y 2019, podrías escribir lo siguiente:



In [ ]:
%%sql
SELECT model, year
FROM products
WHERE year = 2014
OR year = 2016
OR year = 2019;

 * postgresql://postgres:***@localhost:5432/sqlda
3 rows affected.


[('Lemon Limited Edition', 2014), ('Lemon', 2016), ('Bat', 2019)]


Ahora ves los productos que están en años diferentes a los tres mencionados en la declaración SQL.

En la siguiente sección, aprenderás cómo usar la cláusula ORDER BY en tus consultas.

## 1.4.5  Cláusula ORDER BY
En ausencia de instrucciones específicas, las consultas SQL organizarán las filas según el orden en que las encuentre la base de datos. Aunque este comportamiento predeterminado puede ser adecuado en muchos escenarios, en ocasiones es necesario establecer un orden específico.
Por ejemplo, si deseas visualizar todos los productos ordenados por la fecha de su primera producción, desde el más antiguo al más reciente, puedes lograrlo en SQL utilizando la cláusula ORDER BY de la siguiente forma:


In [ ]:
%%sql
-- Como se muestra en la captura de pantalla a continuación,
-- los productos están ordenados por el campo production_start_date.
SELECT model, production_start_date
FROM products
ORDER BY production_start_date;

 * postgresql://postgres:***@localhost:5432/sqlda
12 rows affected.


[('Lemon', datetime.datetime(2012, 10, 28, 0, 0)),
 ('Lemon Limited Edition', datetime.datetime(2013, 8, 30, 0, 0)),
 ('Lemon', datetime.datetime(2015, 12, 27, 0, 0)),
 ('Blade', datetime.datetime(2017, 2, 17, 0, 0)),
 ('Model Chi', datetime.datetime(2017, 2, 17, 0, 0)),
 ('Model Sigma', datetime.datetime(2017, 12, 10, 0, 0)),
 ('Bat', datetime.datetime(2019, 6, 7, 0, 0)),
 ('Model Epsilon', datetime.datetime(2019, 10, 13, 0, 0)),
 ('Bat Limited Edition', datetime.datetime(2019, 10, 13, 0, 0)),
 ('Model Gamma', datetime.datetime(2019, 10, 13, 0, 0)),
 ('Model Chi', datetime.datetime(2021, 10, 1, 0, 0)),
 ('Lemon Zester', datetime.datetime(2021, 10, 1, 0, 0))]


Figura 2.17: Sentencia SELECT con ORDER BY

Si no se menciona explícitamente una secuencia de orden, las filas se devolverán en orden ascendente. Orden ascendente simplemente significa que las filas estarán ordenadas desde el valor más pequeño hasta el valor más alto de la columna o columnas elegidas. En el caso de cosas como el texto, esto significa ordenar en orden alfabético. Puedes hacer el orden ascendente explícito usando la palabra clave ASC. Para la última consulta, esto se podría lograr escribiendo lo siguiente:



In [ ]:
%%sql
SELECT model
FROM products
ORDER BY production_start_date ASC;

 * postgresql://postgres:***@localhost:5432/sqlda
12 rows affected.


[('Lemon',),
 ('Lemon Limited Edition',),
 ('Lemon',),
 ('Blade',),
 ('Model Chi',),
 ('Model Sigma',),
 ('Bat',),
 ('Model Epsilon',),
 ('Bat Limited Edition',),
 ('Model Gamma',),
 ('Model Chi',),
 ('Lemon Zester',)]

Este SQL devolverá el mismo resultado en el mismo orden que el SQL anterior.

Si quieres extraer datos en orden descendente, puedes usar la palabra clave `DESC`. Si quisieras buscar modelos fabricados ordenados de más nuevos a más antiguos, escribirías la siguiente consulta:

El resultado estará ordenado en orden descendente de `production_start_date`, el más reciente primero.


In [ ]:
%%sql
SELECT model, production_start_date
FROM products
ORDER BY production_start_date DESC;

 * postgresql://postgres:***@localhost:5432/sqlda
12 rows affected.


[('Model Chi', datetime.datetime(2021, 10, 1, 0, 0)),
 ('Lemon Zester', datetime.datetime(2021, 10, 1, 0, 0)),
 ('Bat Limited Edition', datetime.datetime(2019, 10, 13, 0, 0)),
 ('Model Epsilon', datetime.datetime(2019, 10, 13, 0, 0)),
 ('Model Gamma', datetime.datetime(2019, 10, 13, 0, 0)),
 ('Bat', datetime.datetime(2019, 6, 7, 0, 0)),
 ('Model Sigma', datetime.datetime(2017, 12, 10, 0, 0)),
 ('Model Chi', datetime.datetime(2017, 2, 17, 0, 0)),
 ('Blade', datetime.datetime(2017, 2, 17, 0, 0)),
 ('Lemon', datetime.datetime(2015, 12, 27, 0, 0)),
 ('Lemon Limited Edition', datetime.datetime(2013, 8, 30, 0, 0)),
 ('Lemon', datetime.datetime(2012, 10, 28, 0, 0))]


Además, en lugar de escribir el nombre de la columna por la que quieres ordenar, puedes referirte al número de posición de esa columna en la cláusula SELECT de la consulta. Por ejemplo, si quisieras devolver todos los modelos en la tabla de productos ordenados por ID de producto, podrías escribir lo siguiente:


In [ ]:
%%sql
SELECT product_id, model
FROM products
ORDER BY product_id;

 * postgresql://postgres:***@localhost:5432/sqlda
12 rows affected.


[(1, 'Lemon'),
 (2, 'Lemon Limited Edition'),
 (3, 'Lemon'),
 (4, 'Model Chi'),
 (5, 'Blade'),
 (6, 'Model Sigma'),
 (7, 'Bat'),
 (8, 'Bat Limited Edition'),
 (9, 'Model Epsilon'),
 (10, 'Model Gamma'),
 (11, 'Model Chi'),
 (12, 'Lemon Zester')]

Este SQL devolverá el mismo resultado que la Figura 2.19.

Finalmente, puedes ordenar por múltiples columnas agregando columnas adicionales después de ORDER BY, separadas con comas. Por ejemplo, quieres ordenar todas las filas en la tabla primero por el año del modelo de más nuevo a más antiguo, y luego por el MSRP de menor a mayor. Entonces escribirías la siguiente consulta:


In [ ]:
%%sql
  SELECT *
  FROM products
  ORDER BY year DESC, base_msrp ASC;

 * postgresql://postgres:***@localhost:5432/sqlda
12 rows affected.


[(12, 'Lemon Zester', 2022, 'scooter', Decimal('349.99'), datetime.datetime(2021, 10, 1, 0, 0), None),
 (11, 'Model Chi', 2022, 'automobile', Decimal('95000.00'), datetime.datetime(2021, 10, 1, 0, 0), None),
 (8, 'Bat Limited Edition', 2020, 'scooter', Decimal('699.99'), datetime.datetime(2019, 10, 13, 0, 0), None),
 (9, 'Model Epsilon', 2020, 'automobile', Decimal('35000.00'), datetime.datetime(2019, 10, 13, 0, 0), None),
 (10, 'Model Gamma', 2020, 'automobile', Decimal('85750.00'), datetime.datetime(2019, 10, 13, 0, 0), None),
 (7, 'Bat', 2019, 'scooter', Decimal('599.99'), datetime.datetime(2019, 6, 7, 0, 0), None),
 (6, 'Model Sigma', 2018, 'automobile', Decimal('65500.00'), datetime.datetime(2017, 12, 10, 0, 0), datetime.datetime(2021, 5, 28, 0, 0)),
 (5, 'Blade', 2017, 'scooter', Decimal('699.99'), datetime.datetime(2017, 2, 17, 0, 0), datetime.datetime(2017, 9, 23, 0, 0)),
 (4, 'Model Chi', 2017, 'automobile', Decimal('115000.00'), datetime.datetime(2017, 2, 17, 0, 0), datetime.datetime(2021, 8, 24, 0, 0)),
 (3, 'Lemon', 2016, 'scooter', Decimal('499.99'), datetime.datetime(2015, 12, 27, 0, 0), datetime.datetime(2021, 8, 24, 0, 0)),
 (2, 'Lemon Limited Edition', 2014, 'scooter', Decimal('799.99'), datetime.datetime(2013, 8, 30, 0, 0), datetime.datetime(2013, 11, 24, 0, 0)),
 (1, 'Lemon', 2013, 'scooter', Decimal('399.99'), datetime.datetime(2012, 10, 28, 0, 0), datetime.datetime(2015, 2, 3, 0, 0))]


Lo siguiente es la salida del código anterior:
Figura 2.20: Ordenando múltiples columnas usando ORDER BY
En la siguiente sección, aprenderás sobre la palabra clave LIMIT en SQL.

## 1.4.6  La Cláusula LIMIT
La mayoría de las tablas en las bases de datos SQL tienden a ser considerablemente grandes, por lo que devolver cada fila individualmente resulta innecesario. En ocasiones, es posible que solo estés interesado en las primeras filas. Para manejar esta situación, entra en juego la palabra clave LIMIT. Supongamos que solo deseas obtener los modelos de los primeros cinco productos que la compañía produjo. Podrías lograrlo utilizando la siguiente consulta:



In [ ]:
%%sql
SELECT model
FROM products
ORDER BY production_start_date
LIMIT 5;

 * postgresql://postgres:***@localhost:5432/sqlda
5 rows affected.


[('Lemon',),
 ('Lemon Limited Edition',),
 ('Lemon',),
 ('Blade',),
 ('Model Chi',)]

Cuando no estás familiarizado con una tabla o consulta, es una preocupación común que al ejecutar una sentencia SELECT accidentalmente se devuelvan muchas filas, lo que puede consumir mucho tiempo y ancho de banda de la máquina. Como precaución habitual, deberías usar la palabra clave LIMIT para recuperar solo un pequeño número de filas cuando ejecutes la consulta por primera vez.

## 1.4.7  Cláusula IS NULL/IS NOT NULL
Frecuentemente, algunas entradas en una columna pueden estar ausentes debido a diversas razones. Quizás los datos no fueron recopilados o no estaban disponibles en el momento de la recopilación. Esta falta de un valor puede reflejar un estado particular en la fila y proporcionar información valiosa.

Independientemente de la causa, a menudo surge el interés por identificar las filas donde los datos no están completos para un valor específico.
- En SQL, los valores en blanco a menudo se representan mediante el término NULL.

Por ejemplo, en la tabla de productos, cuando la columna "production_end_date" tiene un valor NULL, esto indica que el producto aún está en proceso de fabricación. En esta situación, para listar todos los productos que todavía están siendo fabricados, puedes emplear la siguiente consulta:

In [ ]:
%%sql
SELECT *
FROM products
WHERE production_end_date IS NULL;

 * postgresql://postgres:***@localhost:5432/sqlda
6 rows affected.


[(7, 'Bat', 2019, 'scooter', Decimal('599.99'), datetime.datetime(2019, 6, 7, 0, 0), None),
 (8, 'Bat Limited Edition', 2020, 'scooter', Decimal('699.99'), datetime.datetime(2019, 10, 13, 0, 0), None),
 (12, 'Lemon Zester', 2022, 'scooter', Decimal('349.99'), datetime.datetime(2021, 10, 1, 0, 0), None),
 (9, 'Model Epsilon', 2020, 'automobile', Decimal('35000.00'), datetime.datetime(2019, 10, 13, 0, 0), None),
 (10, 'Model Gamma', 2020, 'automobile', Decimal('85750.00'), datetime.datetime(2019, 10, 13, 0, 0), None),
 (11, 'Model Chi', 2022, 'automobile', Decimal('95000.00'), datetime.datetime(2021, 10, 1, 0, 0), None)]

Lo siguiente es el resultado de la consulta:
Figura 2.22: Productos con production_end_date NULL
Si solo te interesan los productos que ya no se están fabricando, puedes usar la cláusula IS NOT NULL, como se muestra en la siguiente consulta:
Lo siguiente es el resultado del código:



In [ ]:
%%sql
SELECT *
FROM products
WHERE production_end_date IS NOT NULL;

 * postgresql://postgres:***@localhost:5432/sqlda
6 rows affected.


[(1, 'Lemon', 2013, 'scooter', Decimal('399.99'), datetime.datetime(2012, 10, 28, 0, 0), datetime.datetime(2015, 2, 3, 0, 0)),
 (2, 'Lemon Limited Edition', 2014, 'scooter', Decimal('799.99'), datetime.datetime(2013, 8, 30, 0, 0), datetime.datetime(2013, 11, 24, 0, 0)),
 (3, 'Lemon', 2016, 'scooter', Decimal('499.99'), datetime.datetime(2015, 12, 27, 0, 0), datetime.datetime(2021, 8, 24, 0, 0)),
 (5, 'Blade', 2017, 'scooter', Decimal('699.99'), datetime.datetime(2017, 2, 17, 0, 0), datetime.datetime(2017, 9, 23, 0, 0)),
 (4, 'Model Chi', 2017, 'automobile', Decimal('115000.00'), datetime.datetime(2017, 2, 17, 0, 0), datetime.datetime(2021, 8, 24, 0, 0)),
 (6, 'Model Sigma', 2018, 'automobile', Decimal('65500.00'), datetime.datetime(2017, 12, 10, 0, 0), datetime.datetime(2021, 5, 28, 0, 0))]


Figura 2.23: Productos con production_end_date no NULL
  
Ahora aprenderás cómo usar estas nuevas palabras clave en el ejercicio siguiente.

## Ejercicio 2.02: Consultando la tabla de vendedores usando palabras clave básicas en una consulta SELECT

Instrucciones

En este ejercicio, crearás varias consultas utilizando palabras clave básicas en una consulta `SELECT`.

Imagina que después de unos días en tu nuevo trabajo, finalmente obtienes acceso a la base de datos de la empresa. Tu jefe te ha pedido que ayudes a un gerente de ventas que no está muy familiarizado con SQL. El gerente de ventas necesita obtener diferentes listas de vendedores.

1. Generar una lista de los primeros 10 vendedores contratados por el concesionario 17, es decir, los vendedores con la fecha de contratación más antigua, ordenados por fecha de contratación, empezando por los más antiguos.
2. Obtener a todos los vendedores contratados en 2021 y 2022, que no han sido dados de baja. Esto implica que la fecha de contratación debe ser posterior al 01-01-2021 y la fecha de terminación debe ser NULL. Ordenar los resultados por fecha de contratación, comenzando por los más recientes.
3. Ayudar al gerente a encontrar un vendedor contratado en 2021, recordando que su primer nombre comienza con "Nic".

Utilizarás tus habilidades en SQL para ayudar al gerente a lograr estos objetivos.

Realiza los siguientes pasos para completar el ejercicio:

1. Examina el esquema de la tabla de vendedores desde la lista desplegable de esquemas. Familiarízate con los nombres de las columnas en la siguiente figura.






In [ ]:
%%sql
SELECT *
FROM
    information_schema.columns
WHERE
    table_name = 'salespeople';

 * postgresql://postgres:***@localhost:5432/sqlda
10 rows affected.


[('sqlda', 'public', 'salespeople', 'salesperson_id', 1, None, 'YES', 'bigint', None, None, 64, 2, 0, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'int8', None, None, None, None, '1', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'salespeople', 'dealership_id', 2, None, 'YES', 'bigint', None, None, 64, 2, 0, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'int8', None, None, None, None, '2', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'salespeople', 'hire_date', 9, None, 'YES', 'timestamp without time zone', None, None, None, None, None, 6, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'timestamp', None, None, None, None, '9', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'salespeople', 'termination_date', 10, None, 'YES', 'timestamp without time zone', None, None, None, None, None, 6, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'timestamp', None, None, None, None, '10', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'salespeople', 'last_name', 5, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '5', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'salespeople', 'suffix', 6, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '6', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'salespeople', 'username', 7, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '7', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'salespeople', 'gender', 8, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '8', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'salespeople', 'title', 3, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '3', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'salespeople', 'first_name', 4, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '4', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES')]

2. Ejecuta la siguiente consulta para obtener los nombres de usuario de los vendedores del concesionario con ID 17, ordenados por sus valores de fecha de contratación, y luego establece LIMIT en 10:

In [ ]:
%%sql
SELECT *
FROM salespeople
WHERE dealership_id = 17
ORDER BY hire_date
LIMIT 10;

 * postgresql://postgres:***@localhost:5432/sqlda
10 rows affected.


[(52, 17, None, 'Bobbi', 'McKeon', None, 'bmckeon1f', 'Female', datetime.datetime(2017, 12, 8, 0, 0), None),
 (88, 17, None, 'Eldin', 'Addenbrooke', None, 'eaddenbrooke2f', 'Male', datetime.datetime(2018, 3, 3, 0, 0), None),
 (189, 17, None, 'Abby', 'Drewery', None, 'adrewery58', 'Male', datetime.datetime(2018, 4, 28, 0, 0), None),
 (249, 17, None, 'Tristan', 'Ainge', None, 'tainge6w', 'Male', datetime.datetime(2018, 8, 11, 0, 0), None),
 (187, 17, None, 'Tyson', 'Kerford', None, 'tkerford56', 'Male', datetime.datetime(2018, 12, 23, 0, 0), None),
 (86, 17, None, 'Willie', 'Gullen', None, 'wgullen2d', 'Male', datetime.datetime(2019, 3, 13, 0, 0), None),
 (3, 17, None, 'Ethyl', 'Sloss', 'IV', 'esloss2', 'Female', datetime.datetime(2019, 4, 7, 0, 0), None),
 (150, 17, None, 'Jermaine', 'Bamell', None, 'jbamell45', 'Female', datetime.datetime(2019, 11, 14, 0, 0), None),
 (1, 17, None, 'Electra', 'Elleyne', None, 'eelleyne0', 'Female', datetime.datetime(2020, 1, 26, 0, 0), None),
 (84, 17, 'Ms', 'Klemens', 'Schneidau', 'II', 'kschneidau2b', 'Male', datetime.datetime(2020, 1, 27, 0, 0), None)]

Ahora tienes la lista de los primeros 10 vendedores contratados por el concesionario 17, es decir, los vendedores con la fecha de contratación más antigua, ordenados por fecha de contratación, empezando por los más antiguos.

3. Ahora, para encontrar a todos los vendedores que fueron contratados en 2021 y 2022 pero que no han sido despedidos, es decir, la fecha de contratación debe ser posterior al 2021-01-01 y la fecha de terminación es nula, ordenados por fecha de contratación, comenzando por los más recientes:



In [ ]:
%%sql
SELECT *
FROM salespeople
WHERE hire_date >= '2021-01-01 00:00:00'
AND termination_date is null
ORDER BY hire_date DESC;

 * postgresql://postgres:***@localhost:5432/sqlda
54 rows affected.


[(226, 20, None, 'Moll', 'Kardos-Stowe', None, 'mkardosstowe69', 'Female', datetime.datetime(2021, 10, 20, 0, 0), None),
 (72, 13, None, 'Neron', 'Hamly', None, 'nhamly1z', 'Male', datetime.datetime(2021, 10, 17, 0, 0), None),
 (163, 1, None, 'Lyda', 'Prine', None, 'lprine4i', 'Female', datetime.datetime(2021, 10, 15, 0, 0), None),
 (254, 2, None, 'Pincus', 'Cowp', None, 'pcowp71', 'Male', datetime.datetime(2021, 10, 13, 0, 0), None),
 (39, 1, None, 'Massimiliano', 'McSpirron', None, 'mmcspirron12', 'Male', datetime.datetime(2021, 10, 9, 0, 0), None),
 (259, 11, None, 'Demetris', 'Gable', None, 'dgable76', 'Male', datetime.datetime(2021, 10, 8, 0, 0), None),
 (243, 17, None, 'Shandie', 'Allderidge', None, 'sallderidge6q', 'Female', datetime.datetime(2021, 9, 30, 0, 0), None),
 (92, 1, 'Rev', 'Sandye', 'Duny', None, 'sduny2j', 'Female', datetime.datetime(2021, 8, 30, 0, 0), None),
 (2, 6, None, 'Montague', 'Alcoran', None, 'malcoran1', 'Male', datetime.datetime(2021, 8, 27, 0, 0), None),
 (76, 16, None, 'Pablo', 'Fleming', None, 'pfleming23', 'Male', datetime.datetime(2021, 8, 26, 0, 0), None),
 (247, 6, None, 'Kahlil', 'Senior', None, 'ksenior6u', 'Male', datetime.datetime(2021, 8, 23, 0, 0), None),
 (117, 9, None, 'Gisela', 'Spurling', None, 'gspurling38', 'Female', datetime.datetime(2021, 8, 21, 0, 0), None),
 (71, 2, None, 'Georgianna', 'Bastian', None, 'gbastian1y', 'Female', datetime.datetime(2021, 8, 19, 0, 0), None),
 (91, 7, None, 'Napoleon', 'Heak', None, 'nheak2i', 'Male', datetime.datetime(2021, 8, 18, 0, 0), None),
 (89, 14, None, 'Letizia', 'Dober', None, 'ldober2g', 'Female', datetime.datetime(2021, 8, 16, 0, 0), None),
 (228, 17, None, 'Blakeley', 'Blaxill', None, 'bblaxill6b', 'Female', datetime.datetime(2021, 8, 13, 0, 0), None),
 (166, 14, None, 'Micah', 'Spalls', None, 'mspalls4l', 'Male', datetime.datetime(2021, 8, 13, 0, 0), None),
 (285, 20, None, 'Rog', 'Wardall', None, 'rwardall7w', 'Male', datetime.datetime(2021, 8, 7, 0, 0), None),
 (122, 16, None, 'Judie', 'Lages', None, 'jlages3d', 'Female', datetime.datetime(2021, 7, 16, 0, 0), None),
 (205, 9, None, 'Wilma', 'Millson', None, 'wmillson5o', 'Female', datetime.datetime(2021, 7, 11, 0, 0), None),
 (132, 10, None, 'Nikolai', 'Lomasney', None, 'nlomasney3n', 'Male', datetime.datetime(2021, 7, 7, 0, 0), None),
 (35, 17, None, 'Agnella', 'Linke', None, 'alinkey', 'Female', datetime.datetime(2021, 6, 19, 0, 0), None),
 (258, 1, None, 'Dorie', 'Dosedale', None, 'ddosedale75', 'Male', datetime.datetime(2021, 6, 11, 0, 0), None),
 (138, 10, None, 'Cathy', 'Rulf', None, 'crulf3t', 'Female', datetime.datetime(2021, 6, 4, 0, 0), None),
 (162, 1, None, 'Cristine', 'Gibbens', None, 'cgibbens4h', 'Female', datetime.datetime(2021, 6, 3, 0, 0), None),
 (103, 7, None, 'Pacorro', 'Howroyd', None, 'phowroyd2u', 'Male', datetime.datetime(2021, 5, 30, 0, 0), None),
 (276, 15, None, 'Corrine', 'Redmire', None, 'credmire7n', 'Female', datetime.datetime(2021, 5, 30, 0, 0), None),
 (23, 2, None, 'Beauregard', 'Peschke', None, 'bpeschkem', 'Male', datetime.datetime(2021, 5, 9, 0, 0), None),
 (158, 18, None, 'Collie', 'Donaway', None, 'cdonaway4d', 'Female', datetime.datetime(2021, 5, 8, 0, 0), None),
 (172, 3, None, 'Bink', 'Kemet', None, 'bkemet4r', 'Male', datetime.datetime(2021, 5, 5, 0, 0), None),
 (130, 15, None, 'Atlante', 'De Bernardis', None, 'adebernardis3l', 'Female', datetime.datetime(2021, 4, 27, 0, 0), None),
 (40, 17, None, 'Bertrando', 'Slay', None, 'bslay13', 'Male', datetime.datetime(2021, 4, 16, 0, 0), None),
 (213, 12, None, 'Kimberlyn', 'Dayce', None, 'kdayce5w', 'Female', datetime.datetime(2021, 4, 3, 0, 0), None),
 (194, 17, None, 'Gillie', 'Constance', None, 'gconstance5d', 'Female', datetime.datetime(2021, 4, 2, 0, 0), None),
 (170, 1, None, 'Giselbert', 'Schule', None, 'gschule4p', 'Male', datetime.datetime(2021, 3, 28, 0, 0), None),
 (283, 13, None, 'Thor', 'Sigmund', None, 'tsigmund7u', 'Male', datetime.datetime(2021, 3, 27, 0, 0), None),
 (82, 17, N

Se devuelven 54 filas de esta consulta SQL. A continuación, se muestran las primeras filas de la salida:

Aquí tienes la traducción al español de tu solicitud:

Ahora, encuentra un vendedor que fue contratado en 2021 y cuyo primer nombre comienza con Nic.


In [ ]:
%%sql
SELECT *
FROM salespeople
WHERE first_name LIKE 'Nic%'
AND hire_date >= '2021-01-01'
AND hire_date <= '2021-12-31';

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[(279, 19, None, 'Nicholle', 'Lisciandri', None, 'nlisciandri7q', 'Female', datetime.datetime(2021, 3, 10, 0, 0), None)]

En este ejercicio, utilizaste varias palabras clave básicas en una consulta SELECT para ayudar al gerente de ventas a obtener una lista de vendedores que necesitaba.

## Actividad 2.01: Consultando la tabla de clientes usando palabras clave básicas en una consulta SELECT
El departamento de marketing ha decidido que quieren llevar a cabo una serie de campañas de marketing para promover una venta. Para hacerlo, necesitan los registros de comunicación por correo electrónico de los clientes de ZoomZoom en el estado de Florida, y los detalles de todos los clientes en la ciudad de Nueva York. También necesitan los números de teléfono de los clientes con órdenes específicas. Los siguientes son los pasos para completar la actividad:
1. Conéctate a la base de datos SQLDA.
2. Examina el esquema de la tabla de `customers` desde la lista desplegable del esquema. Familiarízate con las columnas de esta tabla.
3. Escribe una consulta que recupere todos los correos electrónicos de los clientes de ZoomZoom en el estado de Florida en orden alfabético.
4. Escribe una consulta que obtenga todos los nombres, apellidos y correos electrónicos de los clientes de ZoomZoom en la ciudad de Nueva York, en el estado de Nueva York. Deben ser ordenados alfabéticamente, con el apellido seguido del nombre.
5. Escribe una consulta que devuelva todos los clientes con un número de teléfono ordenados por la fecha en que el cliente fue agregado a la base de datos.

Solucion

1. Examina el esquema de la tabla de clientes desde la lista desplegable del esquema.



In [ ]:
%%sql SELECT * FROM information_schema.columns WHERE table_name = 'customers';

 * postgresql://postgres:***@localhost:5432/sqlda
16 rows affected.


[('sqlda', 'public', 'customers', 'customer_id', 1, None, 'YES', 'bigint', None, None, 64, 2, 0, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'int8', None, None, None, None, '1', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'latitude', 14, None, 'YES', 'double precision', None, None, 53, 2, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'float8', None, None, None, None, '14', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'longitude', 15, None, 'YES', 'double precision', None, None, 53, 2, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'float8', None, None, None, None, '15', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'date_added', 16, None, 'YES', 'timestamp without time zone', None, None, None, None, None, 6, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'timestamp', None, None, None, None, '16', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'suffix', 5, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '5', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'email', 6, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '6', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'gender', 7, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '7', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'ip_address', 8, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '8', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'phone', 9, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '9', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'street_address', 10, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '10', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'city', 11, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '11', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'state', 12, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '12', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('sqlda', 'public', 'customers', 'postal_code', 13, None, 'YES', 'text', None, 1073741824, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'sqlda', 'pg_catalog', 'text', None, None, None, None, '13', 'NO', 'NO', None, None, Non

3. Ejecuta la siguiente consulta para obtener los correos electrónicos de los clientes en el estado de Florida en orden alfabético:

In [ ]:
%%sql
SELECT email
FROM customers
WHERE state='FL'
ORDER BY email LIMIT 10;

 * postgresql://postgres:***@localhost:5432/sqlda
10 rows affected.


[('aachrameevu44@goo.gl',),
 ('aambresinlnt@walmart.com',),
 ('aanstiss12af@eepurl.com',),
 ('aantonove9l@last.fm',),
 ('aarnaudet1v3@cisco.com',),
 ('aarsmithxoe@dion.ne.jp',),
 ('aastle11rg@slate.com',),
 ('aaxelbey77x@cocolog-nifty.com',),
 ('aazemary2f@washingtonpost.com',),
 ('ababarm8m@ow.ly',)]

3. Ejecuta la siguiente consulta para obtener todos los nombres, apellidos y direcciones de correo electrónico de los clientes de ZoomZoom en la ciudad de Nueva York, Nueva York. Los clientes deben ser ordenados alfabéticamente, con el apellido seguido del nombre:

In [ ]:
%%sql
SELECT first_name, last_name, email
FROM customers
WHERE city='New York City' AND state='NY'
ORDER BY last_name, first_name LIMIT 10;

 * postgresql://postgres:***@localhost:5432/sqlda
10 rows affected.


[('Nell', 'Abdy', 'nabdyec4@fema.gov'),
 ('Thomasine', 'Absolon', 'tabsolonomk@forbes.com'),
 ('Ram', 'Acheson', 'racheson1ai@bloglovin.com'),
 ('Pru', 'Achrameev', 'pachrameev2sr@example.com'),
 ('Jandy', 'Adamowicz', 'jadamowiczb1w@clickbank.net'),
 ('Kati', 'Adrian', 'kadrianeem@51.la'),
 ('Orly', 'Aers', 'oaersx61@redcross.org'),
 ('Bradney', 'Aglione', 'baglionee5n@usgs.gov'),
 ('Mellicent', 'Ainslee', 'mainsleeir0@abc.net.au'),
 ('Fergus', 'Aireton', 'fairetonq16@yellowpages.com')]

4. Ejecuta la siguiente consulta para obtener todos los clientes que tienen un número de teléfono, ordenados por la fecha en que el cliente fue agregado a la base de datos:

In [ ]:
%%sql
SELECT *
FROM customers
WHERE phone IS NOT NULL
ORDER BY date_added LIMIT 10;

 * postgresql://postgres:***@localhost:5432/sqlda
10 rows affected.


[(35683, None, 'Betteanne', 'Rulf', None, 'brulfrj6@jalbum.net', 'F', '52.208.248.90', '503-396-8643', '1 Cordelia Crossing', 'Salem', 'OR', '97306', 44.8685, -123.0438, datetime.datetime(2012, 11, 9, 0, 0)),
 (2625, None, 'Binky', 'Dawtrey', None, 'bdawtrey20w@shareasale.com', 'M', '15.75.236.78', '804-990-4322', '0353 Iowa Road', 'Richmond', 'VA', '23208', 37.5593, -77.4471, datetime.datetime(2012, 11, 9, 0, 0)),
 (17099, None, 'Pearla', 'Halksworth', None, 'phalksworthd6y@cyberchimps.com', 'F', '114.138.82.24', '541-198-6063', '130 Marcy Crossing', 'Eugene', 'OR', '97405', 44.0185, -123.0998, datetime.datetime(2012, 11, 9, 0, 0)),
 (30046, None, 'Nanete', 'Hassur', None, 'nhassurn6l@alibaba.com', 'F', '232.115.170.92', '209-364-5939', '13961 Steensland Trail', 'Stockton', 'CA', '95205', 37.9625, -121.2624, datetime.datetime(2012, 11, 9, 0, 0)),
 (18685, None, 'Ingram', 'Crossman', None, 'icrossmanef0@weebly.com', 'M', '207.145.1.202', '503-352-8809', '86 Michigan Junction', 'Salem', 'OR', '97306', 44.8685, -123.0438, datetime.datetime(2012, 11, 9, 0, 0)),
 (6173, None, 'Danila', 'Gristwood', None, 'dgristwood4rg@furl.net', 'F', '254.239.58.108', '832-157-3870', '79865 Hagan Terrace', 'Katy', 'TX', '77493', 29.8678, -95.8298, datetime.datetime(2012, 11, 9, 0, 0)),
 (7486, None, 'Ciro', 'Ferencowicz', None, 'cferencowicz5rx@ucoz.ru', 'M', '8.151.167.184', '786-458-8754', '61 Village Crossing', 'Miami', 'FL', '33111', 25.5584, -80.4582, datetime.datetime(2012, 11, 9, 0, 0)),
 (13390, None, 'Danika', 'Lough', None, 'dloughabx@skype.com', 'F', '188.19.7.207', '212-769-6845', '38463 Forest Dale Way', 'New York City', 'NY', '10019', 40.7651, -73.9858, datetime.datetime(2012, 11, 9, 0, 0)),
 (20253, None, 'Papageno', 'Vella', None, 'pvellafmk@boston.com', 'M', '65.154.68.223', '412-419-6423', None, None, None, None, None, None, datetime.datetime(2012, 11, 10, 0, 0)),
 (8571, None, 'Christina', 'Kenningham', None, 'ckenningham6m2@princeton.edu', 'F', '245.162.246.123', '615-646-6020', '39223 Lunder Street', 'Memphis', 'TN', '38119', 35.0821, -89.8501, datetime.datetime(2012, 11, 10, 0, 0))]

En esta actividad, utilizaste varias palabras clave básicas en una consulta SELECT y ayudaste al gerente de mercadotecnia a obtener los datos que necesitaba para la campaña de mercadotecnia.

# 1.5. Creando Tablas
Ahora que sabes cómo leer datos de tablas, verás cómo crear nuevas tablas. Hay dos maneras de hacerlo: creando tablas en blanco o usando consultas SELECT.
## 1.5.1 Creando Tablas en Blanco
Para crear una nueva tabla en blanco, usas la declaración CREATE TABLE. Esta declaración tiene la siguiente estructura:

In [ ]:
%%sql
CREATE TABLE IF NOT EXISTS mi_tabla (
    column_name_1 INTEGER PRIMARY KEY,
    column_name_2 TEXT NOT NULL,
    column_name_3 TEXT NOT NULL,
    column_name_last INTEGER NOT NULL
);

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]

In [ ]:
%%sql
-- revisamos que la tabla este creada
SELECT table_name FROM information_schema.tables WHERE table_type = 'BASE TABLE'
AND table_schema NOT IN ('pg_catalog', 'information_schema');

 * postgresql://postgres:***@localhost:5432/sqlda
13 rows affected.


[('closest_dealerships',),
 ('countries',),
 ('customer_sales',),
 ('customer_survey',),
 ('customers',),
 ('dealerships',),
 ('emails',),
 ('products',),
 ('public_transportation_by_zip',),
 ('sales',),
 ('salespeople',),
 ('top_cities_data',),
 ('mi_tabla',)]

En este contexto, `{table_name}` representa el nombre de la tabla, `{column_name}` el de la columna, `{data_type}` designa el tipo de dato de dicha columna, y `Basic Data Types of SQL
` se refiere a una o varias palabras clave opcionales que proporcionan características específicas a la columna. Antes de profundizar en el uso de la consulta CREATE TABLE, es esencial familiarizarse con los tipos de datos y las restricciones aplicables a las columnas.

# 1.6 Tipos de Datos Básicos de SQL

Toda columna dentro de una tabla está definida por un tipo de dato. En este segmento, abordaremos los tipos de datos más comunes en PostgreSQL, que comprenden:
- Valores Numéricos
- Texto o Carácter
- Valores Booleanos (Verdadero o Falso)
- Fecha y Tiempo
- Estructuras de Datos (como arreglos y JSON)

## 1.6.1 Numérico
Los tipos de datos numéricos representan números. La siguiente figura proporciona una visión general de algunos de los principales tipos:

<figure>
<center><img src='https://github.com/limspiga/data-modeling/blob/main/images/af2bc6b0-f8fa-4ce3-91a0-7526172aa1e2.png?raw=true' width="600" />
<figcaption>Figure 2.28: Major numeric data types.</figcaption></center>
</figure>

Character
Character data types store text information. The following figure summarizes character data types:

## 1.6.2 Carácter
Los tipos de datos de carácter almacenan información de texto. La siguiente figura resume los tipos de datos de carácter:

<figure>
<center><img src='https://github.com/limspiga/data-modeling/blob/main/images/6ea87a36-32ac-4075-b243-7cfbd5c43dd6.png?raw=true' width="500" />
<figcaption>Figura 2.29: Principales tipos de datos de carácter.</figcaption></center>
</figure>

Internamente, todos los tipos de datos de carácter en SQLite (así como en muchos otros sistemas RDBMS) comparten la misma estructura de datos. El tipo de dato de carácter más utilizado es varchar(n).

## 1.6.2 Booleano
Los booleanos son un tipo de dato utilizado para representar Verdadero o Falso. La siguiente tabla resume los valores que se representan como Booleano cuando se usan en una consulta con un tipo de columna de dato Booleano:

<figure>
<center><img src='https://github.com/limspiga/data-modeling/blob/main/images/e8606409-35fc-47c0-8304-196c28f1a0f3.png?raw=true' width="400" />
<figcaption>Figure 2.30: Accepted Boolean values</figcaption></center>
</figure>

Aunque se aceptan todos estos valores, se recomienda seguir las mejores prácticas usando los valores Verdadero y Falso. Además, los booleanos pueden asumir valores NULL.
## 1.6.3 Fecha y hora (Datetime)

El tipo de dato "fecha y hora" permite almacenar información temporal, como fechas y momentos específicos. A continuación, se presentan ejemplos de estos tipos de datos:

<figure>
<center><img src='https://github.com/limspiga/data-modeling/blob/main/images/7f0b75cf-4d20-4ac1-a16d-aab231dbf3f4.png?raw=true' width="600" />
<figcaption>Figura 2.31: Tipos de datos fecha y hora populares</figcaption></center>
</figure>


# 1.7 Estructuras de Datos: JSON y Arreglos

Muchas versiones modernas de SQL también admiten estructuras de datos, como el Formato de Objeto de Notación JavaScript (JSON) y arreglos. Los arreglos son simplemente listas de datos, usualmente escritos como elementos encerrados entre corchetes. Por ejemplo, ['gato', 'perro', 'caballo'] es un arreglo. Un objeto JSON es una serie de pares clave-valor separados por comas y encerrados entre llaves. Por ejemplo, {'nombre': 'Bob', 'edad': 27, 'ciudad': 'Nueva York'} es un objeto JSON válido. Estas estructuras de datos aparecen constantemente en aplicaciones tecnológicas, y poder usarlas en una base de datos facilita la realización de muchos tipos de análisis.
Explorarás las estructuras de datos con más detalle en el Capítulo 7, Análisis Usando Tipos de Datos Complejos. Antes de eso, aprenderás sobre algunas operaciones básicas en un RDBMS usando SQL.






# 1.8 Restricciones de Columna
Las restricciones de columna son palabras clave que te ayudan a especificar las propiedades que deseas atribuir a una columna en particular. En otras palabras, puedes asegurarte de que todas las filas en esa columna cumplan con la restricción especificada. Algunas de las principales restricciones de columna son las siguientes:

- NOT NULL: Esta restricción garantiza que ningún valor en una columna pueda ser NULL.
- UNIQUE: Esta restricción garantiza que cada fila para una columna tenga un valor único y que ningún valor se repita.
• PRIMARY KEY: Esta es una restricción especial que es única para cada fila y te ayuda a encontrar una fila específica más rápidamente. Si la clave primaria de esta tabla contiene solo una columna, puedes agregar esta restricción PRIMARY KEY a la definición de la columna de la clave primaria. Si la clave primaria de esta tabla consta de varias columnas, necesitas usar una restricción de tabla para definir la clave en la declaración CREATE.


## 1.8.1  Declaración CREATE Simple

Ahora que conoces sobre los tipos de datos y restricciones de columna, puedes empezar a crear tu primera tabla. Supongamos que quieres crear una tabla llamada poblaciones_estados con columnas para las iniciales y poblaciones de los estados. La consulta se vería así:


Figura 2.32: Declaración CREATE simple


In [ ]:
%%sql
CREATE TABLE state_populations (
  state VARCHAR(2) PRIMARY KEY,
  population NUMERIC
);

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]





Una vez que ejecutes esta declaración, puedes ejecutar una simple consulta SELECT para verificar que la tabla ha sido creada. Sin embargo, no verás ninguna fila en la salida ya que no has ejecutado ninguna declaración para poblarla.

Nota

A veces, puedes ejecutar una consulta CREATE TABLE y obtener el error relation {nombre_tabla} already exists. Esto simplemente significa que ya existe una tabla con el mismo nombre. Debes eliminar la tabla con el mismo nombre o cambiar el nombre de tu tabla. Aprenderás cómo eliminar una tabla más adelante en este capítulo.


Pronto explorarás la segunda forma de crear una tabla, que es mediante una consulta SQL. Pero primero, realizarás un ejercicio para crear una tabla en blanco en SQL.

##  Ejercicio 2.03: Creación de la Tabla countries en SQL

En este ejercicio, el objetivo es crear una tabla en la base de datos para almacenar información sobre diferentes países. Esta tabla será útil para el equipo de marketing de ZoomZoom que quiere analizar datos específicos de diversos países.

Sigue estos pasos para completar el ejercicio:
1. Ejecuta la siguiente consulta para eliminar la tabla "countries" ya que ya existe en la base de datos:


In [ ]:
%%sql
DROP TABLE IF EXISTS countries;

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]

2. Ejecuta la siguiente consulta para crear la tabla "countries":

In [ ]:
%%sql
    CREATE TABLE countries (
      key INT PRIMARY KEY,
      name text UNIQUE,
      founding_year INT,
      capital text
    );

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]

Deberías obtener un mensaje de resultado como el siguiente, que indica la creación de una tabla en blanco:

En este ejercicio, aprendiste cómo crear una tabla utilizando diferentes restricciones de columna y la declaración CREATE TABLE. En la siguiente sección, crearás tablas utilizando la consulta SELECT.


## 1.8.2 Creando Tablas con SELECT
Ya sabes cómo crear una tabla. Sin embargo, supongamos que quisieras crear una tabla utilizando datos de una tabla existente. Esto se puede hacer utilizando una modificación de la declaración CREATE TABLE:

```sql
CREATE TABLE {table_name} AS (
  {select_query}
);

```

Aquí, {select_query} es cualquier consulta SELECT que pueda ejecutarse en tu base de datos. Por ejemplo, supongamos que quisieras crear una tabla basada en la tabla de productos que solo tuviera productos del año 2014. Supón que el título de la tabla es products_2014; podrías escribir la siguiente consulta:

In [ ]:
%%sql
CREATE TABLE products_2014 AS
SELECT *
FROM products
WHERE year = 2014;

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[]

Esto se puede hacer con cualquier consulta, y la tabla heredará todas las propiedades de la consulta de salida.
Sqlite también ofrece otra forma de crear una tabla a partir de una consulta, que utiliza una sintaxis SELECT ... INTO ... . A continuación, se muestra un ejemplo de esta sintaxis:

Un desafío que surge al crear una tabla mediante una consulta es que no se definen de forma explícita los tipos de datos, lo cual puede generar confusión.

In [ ]:
%%sql
SELECT  column_name,  data_type,  character_maximum_length,  column_default, is_nullable
FROM  information_schema.columns WHERE table_name = 'products_2014';

 * postgresql://postgres:***@localhost:5432/sqlda
7 rows affected.


[('production_start_date', 'timestamp without time zone', None, None, 'YES'),
 ('production_end_date', 'timestamp without time zone', None, None, 'YES'),
 ('year', 'bigint', None, None, 'YES'),
 ('product_id', 'bigint', None, None, 'YES'),
 ('base_msrp', 'numeric', None, None, 'YES'),
 ('product_type', 'text', None, None, 'YES'),
 ('model', 'text', None, None, 'YES')]

A partir del resultado, puedes identificar todas las columnas y sus tipos de datos en la tabla products_2014.

# 1.9 Actualizando Tablas
Con el tiempo, es posible que necesites modificar una tabla agregando columnas, incorporando nuevos datos o actualizando filas existentes. Esta sección te ayudará a comprender cómo hacerlo.

### Agregando y Removiendo Columnas
Para agregar nuevas columnas a una tabla existente, utilizas la instrucción ALTER TABLE ... ADD COLUMN, como se muestra en la siguiente consulta:
```sql
ALTER TABLE {table_name}
ADD COLUMN {column_name} {data_type};
```

Por ejemplo, si quisieras agregar una nueva columna a la tabla products_2014 que usarás para almacenar el peso de los productos en kilogramos llamada weight, podrías hacerlo utilizando la siguiente consulta:



In [ ]:
%%sql
ALTER TABLE products_2014
ADD COLUMN weight INT;

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]

Esta consulta creará una nueva columna llamada weight en la tabla products_2014 y le asignará el tipo de dato entero, de modo que solo se puedan almacenar enteros en ella.

Si quieres eliminar una columna de una tabla, puedes usar la instrucción ALTER TABLE ... DROP COLUMN:
```sql
ALTER TABLE {table_name}
DROP COLUMN {column_name};
```
Aquí, {table_name} es el nombre de la tabla que deseas modificar, y {column_name} es el nombre de la columna que quieres eliminar. Imagina que decides eliminar la columna weight que acabas de crear. Podrías deshacerte de ella utilizando la siguiente consulta:


In [ ]:
%%sql
ALTER TABLE products_2014
DROP COLUMN weight;

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]

Como puedes ver en la captura de pantalla a continuación, la columna ha sido eliminada

In [ ]:
%%sql
SELECT  column_name,  data_type,  character_maximum_length,  column_default, is_nullable
FROM  information_schema.columns WHERE table_name = 'products_2014';

 * postgresql://postgres:***@localhost:5432/sqlda
7 rows affected.


[('production_start_date', 'timestamp without time zone', None, None, 'YES'),
 ('production_end_date', 'timestamp without time zone', None, None, 'YES'),
 ('year', 'bigint', None, None, 'YES'),
 ('product_id', 'bigint', None, None, 'YES'),
 ('base_msrp', 'numeric', None, None, 'YES'),
 ('product_type', 'text', None, None, 'YES'),
 ('model', 'text', None, None, 'YES')]

## 1.9.1 Agregando Nuevos Datos
Puedes agregar nuevos datos a una tabla utilizando varios métodos en SQL. Uno de esos métodos es simplemente insertar valores directamente en una tabla usando la declaración INSERT INTO... VALUES. Tiene la siguiente estructura:

```sql
INSERT INTO {table_name} (
  {column_1], {column_2}, ...{column_last}
)
VALUES (
  {column_value_1}, {column_value_2}, ... {column_value_last}
);
```
Aquí, {table_name} es el nombre de la tabla en la que deseas insertar tus datos, {column_1}, {column_2}, ... {column_last} es una lista de las columnas cuyos valores quieres insertar, y {column_value_1}, {column_value_2}, ... {column_value_last} es la lista de valores que deseas insertar en la tabla. Si una columna en la tabla no se incluye en la declaración INSERT, se asume que la columna tiene un valor NULL.

Por ejemplo, supongamos que quieres insertar una nueva entrada para un scooter en la tabla products_2014. Esto se puede hacer con la siguiente consulta:


In [ ]:
%%sql
INSERT INTO products_2014 (
product_id, model, year,
  product_type, base_msrp,
  production_start_date, production_end_date
)
VALUES (
  14, 'Nimbus 5000', 2014,
  'scooter', 500.00,
  '2014-03-03', '2020-03-03'
);

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[]

Esta consulta agrega una nueva fila a la tabla products_2014 en consecuencia. Puedes ejecutar una consulta SELECT para ver todas las filas en la tabla:

In [ ]:
%%sql
SELECT * FROM products_2014;

 * postgresql://postgres:***@localhost:5432/sqlda
2 rows affected.


[(2, 'Lemon Limited Edition', 2014, 'scooter', Decimal('799.99'), datetime.datetime(2013, 8, 30, 0, 0), datetime.datetime(2013, 11, 24, 0, 0)),
 (14, 'Nimbus 5000', 2014, 'scooter', Decimal('500.00'), datetime.datetime(2014, 3, 3, 0, 0), datetime.datetime(2020, 3, 3, 0, 0))]

Otra forma de insertar datos en una tabla es usar la declaración INSERT con una consulta SELECT utilizando la siguiente sintaxis:


```sql
INSERT INTO {table_name} ({column_1], {column_2}, ...{column_last})
{select_query};
```

Aquí, {table_name} es el nombre de la tabla en la que deseas insertar los datos, {column_1}, {column_2}, ... {column_last} es una lista de las columnas cuyos valores quieres insertar, y {select_query} es una consulta con la misma estructura que los valores que deseas insertar en la tabla.

Toma el ejemplo de la tabla products_2014. La has creado con una consulta SELECT con una fila. Anteriormente en esta sección, has insertado una fila en ella. Por lo tanto, ahora contiene dos filas. Si también deseas insertar los productos de 2016, podrías usar la siguiente consulta, que inserta una fila más en la tabla:




In [ ]:
%%sql
SELECT *
FROM products
WHERE year=2016;

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[(3, 'Lemon', 2016, 'scooter', Decimal('499.99'), datetime.datetime(2015, 12, 27, 0, 0), datetime.datetime(2021, 8, 24, 0, 0))]

In [ ]:
%%sql
INSERT INTO products_2014(
  product_id, model, year, product_type, base_msrp,
  production_start_date, production_end_date
)
SELECT*
FROM products
WHERE year=2016;

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[]

In [ ]:
%%sql
SELECT * FROM products_2014;

 * postgresql://postgres:***@localhost:5432/sqlda
3 rows affected.


[(2, 'Lemon Limited Edition', 2014, 'scooter', Decimal('799.99'), datetime.datetime(2013, 8, 30, 0, 0), datetime.datetime(2013, 11, 24, 0, 0)),
 (14, 'Nimbus 5000', 2014, 'scooter', Decimal('500.00'), datetime.datetime(2014, 3, 3, 0, 0), datetime.datetime(2020, 3, 3, 0, 0)),
 (3, 'Lemon', 2016, 'scooter', Decimal('499.99'), datetime.datetime(2015, 12, 27, 0, 0), datetime.datetime(2021, 8, 24, 0, 0))]

Ahora contiene tres filas de tres diferentes formas de insertar datos: una fila de CREATE como resultado de una consulta SELECT, una fila de INSERT con datos, y una fila de INSERT utilizando el resultado de una consulta SELECT.


## 1.9.2  Actualizando Filas Existentes
A veces, es posible que necesites actualizar los valores de los datos presentes en una tabla. Para hacer esto, puedes usar la declaración `UPDATE`:

```sql
UPDATE {table_name} SET
  {column_1} = {column_value_1},
  {column_2} = {column_value_2},
  ...
  {column_last} = {column_value_last}
WHERE {conditional};
```



Aquí, {table_name} es el nombre de la tabla cuyos datos serán modificados, {column_1}, {column_2},... {column_last} es la lista de columnas cuyos valores deseas cambiar, {column_value_1}, {column_value_2}, ... {column_value_last} es la lista de nuevos valores que deseas actualizar en esas columnas, y {WHERE} es una declaración condicional similar a la que encontrarías en una consulta SELECT.
Para ilustrar el uso de la instrucción UPDATE, imagina que, por el resto del año, la compañía ha decidido vender todos los modelos de scooters anteriores a 2018 por $299.99. Podrías cambiar los datos en la tabla products_2014 utilizando la siguiente consulta:

In [ ]:
%%sql
UPDATE Products_2014 SET
  base_msrp = 299.99
WHERE product_type = 'scooter'
AND year<2018;

 * postgresql://postgres:***@localhost:5432/sqlda
3 rows affected.


[]

In [ ]:
%%sql
SELECT *
FROM Products_2014
WHERE product_type = 'scooter'
AND year<2018;

 * postgresql://postgres:***@localhost:5432/sqlda
3 rows affected.


[(2, 'Lemon Limited Edition', 2014, 'scooter', Decimal('299.99'), datetime.datetime(2013, 8, 30, 0, 0), datetime.datetime(2013, 11, 24, 0, 0)),
 (14, 'Nimbus 5000', 2014, 'scooter', Decimal('299.99'), datetime.datetime(2014, 3, 3, 0, 0), datetime.datetime(2020, 3, 3, 0, 0)),
 (3, 'Lemon', 2016, 'scooter', Decimal('299.99'), datetime.datetime(2015, 12, 27, 0, 0), datetime.datetime(2021, 8, 24, 0, 0))]

Esta consulta produce el siguiente resultado. Puedes ver que la columna base_msrp de los tres registros ha sido actualizada a 299.99 porque todos son scooters fabricados antes de 2018.

## Ejercicio 2.04: Actualizando la tabla para aumentar el precio de un vehículo

Durante este ejercicio, realizarás modificaciones en una tabla utilizando el comando UPDATE. A raíz del incremento en el precio de los metales escasos utilizados en la fabricación de vehículos eléctricos, el Modelo Chi de 2022 experimentará un ajuste de precio del 10%, llevando su valor actual de $95,000 a un nuevo monto.

En situaciones cotidianas, simplemente se ajustaría el precio en la tabla de productos. No obstante, ya que continuaremos utilizando la base de datos sqlda a lo largo del libro, es recomendable preservar los valores originales para asegurar la coherencia de los resultados SQL. Por ello, optaremos por generar tablas adicionales para ejemplificar las operaciones con los comandos INSERT, ALTER, UPDATE, DELETE y DROP.

Realiza los siguientes pasos para completar el ejercicio:

1. Ejecuta la siguiente consulta para crear una tabla product_2022 a partir de la tabla de productos:

In [ ]:
%%sql
CREATE TABLE products_2022 AS
SELECT *
FROM products
WHERE year=2022;

 * postgresql://postgres:***@localhost:5432/sqlda
2 rows affected.


[]

Ejecuta la siguiente consulta para actualizar el precio del Modelo Chi en un 10% en la tabla products_2022:

In [ ]:
%%sql
SELECT *
FROM products_2022
WHERE model='Model Chi'
AND year=2022;

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[(11, 'Model Chi', 2022, 'automobile', Decimal('95000.00'), datetime.datetime(2021, 10, 1, 0, 0), None)]

In [ ]:
%%sql
UPDATE Products_2022 SET
  base_msrp = base_msrp*1.10
WHERE model='Model Chi'
AND year=2022;

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[]

4. Escribe la consulta SELECT para verificar si el precio del Modelo Chi en 2022 ha sido actualizado:

In [ ]:
%%sql
SELECT *
FROM products_2022
WHERE model='Model Chi'
AND year=2022;

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[(11, 'Model Chi', 2022, 'automobile', Decimal('104500.0000'), datetime.datetime(2021, 10, 1, 0, 0), None)]

Como puedes ver en el resultado, el precio del Modelo Chi ahora es de $104,500; anteriormente era de \$95,000.

## 1.9.3   Gestión de Datos: Eliminación y Actualización
Con el tiempo, es común encontrarse con datos en una tabla que ya no son relevantes o han quedado obsoletos. En estas situaciones, se vuelve esencial poder eliminar o actualizar estos datos.

### 1.9.3.1  Cómo Suprimir Valores Específicos de una Fila
En determinadas circunstancias, quizás necesites eliminar un valor específico dentro de una fila. Una manera sencilla de hacerlo es mediante el uso del comando UPDATE, estableciendo el valor de la columna deseada en NULL:



```sql
UPDATE {table_name} SET
  {column_1} = NULL,
  {column_2} = NULL,
  ...
  {column_last} = NULL
WHERE {conditional};
```



Aquí, {table_name} es el nombre de la tabla con los datos que necesitan ser modificados, {column_1}, {column_2},... {column_last} es la lista de columnas cuyos valores quieres eliminar, y {WHERE} es una declaración condicional como la que encontrarías en una consulta SELECT.

Por ejemplo, tienes la dirección de correo electrónico incorrecta registrada para el cliente con el ID de cliente igual a 3. Para corregir eso, puedes usar la siguiente consulta:

In [ ]:
%%sql
  SELECT email
  FROM customers
  WHERE customer_id=3;

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[('bjordan2@geocities.com',)]

In [ ]:
%%sql
UPDATE customers SET
  email = NULL
WHERE customer_id=3;

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[]

In [ ]:
%%sql
  SELECT email
  FROM customers
  WHERE customer_id=3;

 * postgresql://postgres:***@localhost:5432/sqlda
1 rows affected.


[(None,)]

Sin embargo, podría haber casos en los que necesites eliminar filas de una tabla. Por ejemplo, en la base de datos, tienes una fila etiquetada como cliente de prueba, que ya no es necesaria y debe ser eliminada. En la siguiente sección, aprenderás cómo eliminar filas de una tabla.

## 1.9.4 Eliminando Filas de una Tabla
Eliminar una fila de una tabla se puede hacer utilizando la declaración DELETE, que tiene el siguiente aspecto:
```sql
DELETE FROM {table_name}
WHERE {condition};
```
Por ejemplo, debes eliminar los productos cuyo tipo (product_type) es scooter de la tabla products_2014. Para hacerlo, puedes usar la siguiente consulta:


In [ ]:
%%sql
DELETE FROM products_2014
WHERE product_type='scooter';

 * postgresql://postgres:***@localhost:5432/sqlda
3 rows affected.


[]

In [ ]:
%%sql
SELECT * FROM products_2014;

 * postgresql://postgres:***@localhost:5432/sqlda
0 rows affected.


[]


En las últimas secciones, has insertado tres productos en esta tabla, todos ellos scooters. Después de ejecutar la declaración DELETE, PostgreSQL muestra que no había ningún producto en esta tabla ya que todos los registros son eliminados.

Si deseas eliminar todos los datos en la tabla products_2014 sin borrar la tabla, podrías escribir la siguiente consulta, que es DELETE sin ninguna condición:

In [ ]:
%%sql
DELETE FROM products_2014;

 * postgresql://postgres:***@localhost:5432/sqlda
0 rows affected.


[]

In [ ]:
%%sql
SELECT * FROM products_2014;

 * postgresql://postgres:***@localhost:5432/sqlda
0 rows affected.


[]

## 1.9.5 Eliminando Tablas
Para eliminar todos los datos de una tabla y la tabla misma, puedes usar simplemente la instrucción DROP TABLE con la siguiente sintaxis:

```sql
DROP TABLE {nombre_tabla};
```
Aquí, {nombre_tabla} es el nombre de la tabla que deseas eliminar. Si quisieras eliminar todos los datos en la tabla products_2014 junto con la tabla en sí, escribirías lo siguiente:

In [ ]:
%%sql
DROP TABLE products_2014;

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]

In [ ]:
%%sql
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_type = 'BASE TABLE'
AND table_schema NOT IN ('pg_catalog', 'information_schema');

 * postgresql://postgres:***@localhost:5432/sqlda
15 rows affected.


[('public', 'closest_dealerships'),
 ('public', 'customer_sales'),
 ('public', 'customer_survey'),
 ('public', 'customers'),
 ('public', 'dealerships'),
 ('public', 'emails'),
 ('public', 'products'),
 ('public', 'public_transportation_by_zip'),
 ('public', 'sales'),
 ('public', 'salespeople'),
 ('public', 'top_cities_data'),
 ('public', 'mi_tabla'),
 ('public', 'state_populations'),
 ('public', 'countries'),
 ('public', 'products_2022')]

Si intentas leer de esta tabla, recibirás un mensaje de error de SQlite indicándote que la tabla no existe.

In [ ]:
%%sql
DROP TABLE IF EXISTS products_2014;

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]

El comando DROP TABLE IF EXISTS es útil para automatizar scripts SQL, especialmente antes de un CREATE TABLE. Si una tabla ya existe, intentar crearla nuevamente generará un error. Utilizar DROP TABLE IF EXISTS antes de CREATE TABLE asegura que cualquier tabla previa con el mismo nombre sea eliminada antes de intentar crear una nueva. Aunque es práctico en operaciones donde se usan tablas temporales, hay que tener precaución para no eliminar tablas importantes. Por ello, generalmente se usa solo en entornos de procesamiento de datos automatizados.

## Ejercicio 2.05: Eliminando una Tabla de Referencia Innecesaria

En este ejercicio, te familiarizarás con el proceso de eliminación de una tabla a través de SQL. Imagina que el equipo de marketing ya culminó su análisis sobre el número potencial de clientes por estado y, por lo tanto, ya no requiere la tabla state_populations. Con el propósito de optimizar el espacio en la base de datos, es pertinente eliminar dicha tabla. Si aún no has generado esta tabla, te sugiero volver a la sección "Simple CREATE Statement" de este capítulo y hacerlo. Sigue estos pasos para llevar a cabo el ejercicio:

1. Ejecuta la siguiente consulta para eliminar la tabla state_populations:

In [ ]:
%%sql
DROP TABLE state_populations;

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]



   
2. Verifica que la tabla state_populations haya sido eliminada de la base de datos.

In [ ]:
%%sql
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_type = 'BASE TABLE'
AND table_schema NOT IN ('pg_catalog', 'information_schema');

 * postgresql://postgres:***@localhost:5432/sqlda
14 rows affected.


[('public', 'closest_dealerships'),
 ('public', 'customer_sales'),
 ('public', 'customer_survey'),
 ('public', 'customers'),
 ('public', 'dealerships'),
 ('public', 'emails'),
 ('public', 'products'),
 ('public', 'public_transportation_by_zip'),
 ('public', 'sales'),
 ('public', 'salespeople'),
 ('public', 'top_cities_data'),
 ('public', 'mi_tabla'),
 ('public', 'countries'),
 ('public', 'products_2022')]


3. Dado que la tabla acaba de ser eliminada, una consulta SELECT en esta tabla generará un error, como se esperaba:
Verás el error mostrado en la siguiente figura:
Figura 2.45: Error mostrado ya que la tabla state_populations fue eliminada.


In [ ]:
%%sql
SELECT *
FROM state_populations;

 * postgresql://postgres:***@localhost:5432/sqlda
(psycopg2.errors.UndefinedTable) relation "state_populations" does not exist
LINE 2: FROM state_populations;
             ^

[SQL: SELECT *
FROM state_populations;]
(Background on this error at: https://sqlalche.me/e/20/f405)


4. Además, elimina la tabla products_2022 que fue creada anteriormente para mantener la base de datos limpia:
    DROP TABLE products_2022;

  SELECT *
FROM state_populations;
.

In [ ]:
%%sql
DROP TABLE products_2022;

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]

En este ejercicio, aprendiste cómo eliminar una tabla usando la declaración DROP TABLE. En la siguiente actividad, pondrás a prueba las habilidades que adquiriste al crear y modificar tablas usando SQL

## Actividad 2.02: Creación y Modificación de Tablas para Operaciones de Marketing

En esta actividad, pondrás a prueba tu habilidad para crear y modificar tablas usando SQL.

Realizaste un trabajo sobresaliente al recopilar datos para el equipo de marketing. No obstante, el gerente de marketing, al cual asististe, identificó un error en su solicitud. En vez de requerir únicamente una consulta, necesita establecer una nueva tabla dentro de la base de datos analítica de la empresa. Asimismo, es esencial hacer ciertas modificaciones a los datos existentes en la tabla de clientes. Tu misión es apoyar al gerente de marketing en la gestión de esta tabla.

1. Crea una nueva tabla llamada customers_nyc que extraiga todas las filas de la tabla de clientes donde el cliente vive en la Ciudad de Nueva York, en el estado de Nueva York.
2. Elimina todos los clientes con el código postal 10014 de la nueva tabla. Debido a leyes locales, no serán elegibles para marketing.
3. Añade una nueva columna de texto llamada evento.
4. Establece el valor de la columna evento a fiesta de agradecimiento.

A continuación, se muestra la salida esperada:

<figure>
<center><img src='https://github.com/limspiga/data-modeling/blob/main/images/55e3a327-4203-4bf6-b304-001eaefb5a7c.png?raw=true' width="600" />
<figcaption>Figura 2.46: La tabla customers_nyc con el evento establecido en "fiesta de agradecimiento".</figcaption></center>
</figure>


Le informas al gerente que has completado estos pasos. Él le dice al equipo de operaciones de marketing, quienes luego utilizan los datos para lanzar una campaña de marketing. Posteriormente, el gerente de marketing te pide que elimines la tabla customers_nyc.

En esta actividad, utilizaste diferentes operaciones CRUD para modificar una tabla según lo solicitado por el gerente de marketing. Ahora cerrarás el círculo para explorar cómo se conectan SQL y la analítica.

**Solución**

1. Ejecuta la siguiente consulta para crear la tabla con los clientes de la Ciudad de Nueva York:

In [ ]:
%%sql
CREATE TABLE customers_nyc AS
SELECT *
FROM customers
WHERE city='New York City'
AND state='NY';

 * postgresql://postgres:***@localhost:5432/sqlda
731 rows affected.


[]

2. Ejecute el siguiente código para ver el resultado:

In [ ]:
%%sql
SELECT * FROM customers_nyc LIMIT 10;

 * postgresql://postgres:***@localhost:5432/sqlda
10 rows affected.


[(52, None, 'Giusto', 'Backe', None, 'gbacke1f@digg.com', 'M', '26.56.68.189', '212-959-9172', '6 Onsgard Terrace', 'New York City', 'NY', '10131', 40.7808, -73.9772, datetime.datetime(2013, 3, 2, 0, 0)),
 (162, None, 'Artair', 'Betchley', None, 'abetchley4h@dagondesign.com', 'M', '108.147.128.250', None, '7 Boyd Road', 'New York City', 'NY', '10090', 40.7808, -73.9772, datetime.datetime(2017, 2, 19, 0, 0)),
 (374, None, 'Verge', 'Esel', None, 'veselad@vistaprint.com', 'M', '58.238.20.156', '917-653-2378', '6 Algoma Park', 'New York City', 'NY', '10014', 40.7339, -74.0054, datetime.datetime(2018, 10, 14, 0, 0)),
 (406, None, 'Rozina', 'Jeal', None, 'rjealb9@howstuffworks.com', 'F', '50.235.32.29', '917-610-2582', '64653 Homewood Terrace', 'New York City', 'NY', '10105', 40.7628, -73.9785, datetime.datetime(2013, 5, 12, 0, 0)),
 (456, 'Rev', 'Cybil', 'Noke', None, 'cnokecn@jigsy.com', 'F', '5.31.139.106', '212-306-6098', '88 Sycamore Parkway', 'New York City', 'NY', '10260', 40.7808, -73.9772, datetime.datetime(2019, 9, 18, 0, 0)),
 (472, None, 'Rawley', 'Yegorov', None, 'ryegorovd3@google.es', 'M', '183.199.243.74', '212-560-1255', '872 Old Shore Parkway', 'New York City', 'NY', '10034', 40.8662, -73.9221, datetime.datetime(2017, 7, 21, 0, 0)),
 (496, None, 'Layton', 'Spolton', None, 'lspoltondr@free.fr', 'M', '108.112.8.165', '646-900-8237', '7 Old Gate Drive', 'New York City', 'NY', '10024', 40.7864, -73.9764, datetime.datetime(2013, 8, 16, 0, 0)),
 (1028, None, 'Issy', 'Andrieux', None, 'iandrieuxsj@dell.com', 'F', '199.50.5.37', '212-206-7889', '33337 Dahle Way', 'New York City', 'NY', '10115', 40.8111, -73.9642, datetime.datetime(2020, 7, 24, 0, 0)),
 (1037, None, 'Magdalene', 'Veryard', None, 'mveryardss@behance.net', 'F', '93.201.129.213', None, '41028 Katie Junction', 'New York City', 'NY', '10039', 40.8265, -73.9383, datetime.datetime(2016, 10, 29, 0, 0)),
 (1063, None, 'Juliet', 'Beadles', None, 'jbeadlesti@time.com', 'F', '47.96.88.226', '212-645-4677', '34984 Goodland Point', 'New York City', 'NY', '10120', 40.7506, -73.9894, datetime.datetime(2017, 4, 13, 0, 0))]

3. Ejecute la siguiente consulta para eliminar usuarios con el código postal 10014:


In [ ]:
%%sql
DELETE FROM customers_nyc
WHERE postal_code='10014';

 * postgresql://postgres:***@localhost:5432/sqlda
27 rows affected.


[]

4. Ejecute la siguiente consulta para agregar la nueva columna de evento:


In [ ]:
%%sql
ALTER TABLE customers_nyc
ADD COLUMN event text;

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]

5. Actualice la tabla customers_nyc y establezca la columna de evento a "fiesta de agradecimiento" utilizando la siguiente consulta:


In [ ]:
%%sql
UPDATE customers_nyc SET
event = 'thank-you party';

 * postgresql://postgres:***@localhost:5432/sqlda
704 rows affected.


[]

6. Ejecute el siguiente código para ver el resultado:


In [ ]:
%%sql
SELECT *
FROM customers_nyc;

 * postgresql://postgres:***@localhost:5432/sqlda
704 rows affected.


[(52, None, 'Giusto', 'Backe', None, 'gbacke1f@digg.com', 'M', '26.56.68.189', '212-959-9172', '6 Onsgard Terrace', 'New York City', 'NY', '10131', 40.7808, -73.9772, datetime.datetime(2013, 3, 2, 0, 0), 'thank-you party'),
 (4535, None, 'Alejandra', 'Jinda', None, 'ajinda3hy@w3.org', 'F', '232.155.209.216', '347-488-5351', '3475 Kedzie Plaza', 'New York City', 'NY', '10280', 40.7105, -74.0163, datetime.datetime(2014, 1, 30, 0, 0), 'thank-you party'),
 (7196, None, 'Patrice', 'Yarker', None, 'pyarker5jv@diigo.com', 'F', '96.131.45.42', '212-975-0572', '2222 Killdeer Park', 'New York City', 'NY', '10175', 40.7543, -73.9798, datetime.datetime(2019, 4, 30, 0, 0), 'thank-you party'),
 (10067, None, 'Etheline', 'Gledstane', None, 'egledstane7rm@google.ca', 'F', '22.161.22.209', None, '124 3rd Trail', 'New York City', 'NY', '10160', 40.7808, -73.9772, datetime.datetime(2012, 12, 24, 0, 0), 'thank-you party'),
 (10119, None, 'Carolann', 'Hodgen', None, 'chodgen7t2@blogs.com', 'F', '245.199.221.245', '212-865-8370', '63 Waywood Center', 'New York City', 'NY', '10150', 40.7808, -73.9772, datetime.datetime(2017, 1, 9, 0, 0), 'thank-you party'),
 (12951, None, 'Filberte', 'Jannequin', 'II', 'fjannequin9zq@sogou.com', 'M', '41.156.149.153', '212-862-7926', '6 Florence Point', 'New York City', 'NY', '10090', 40.7808, -73.9772, datetime.datetime(2013, 3, 27, 0, 0), 'thank-you party'),
 (13212, None, 'Polly', 'Greenshiels', None, 'pgreenshielsa6z@yale.edu', 'F', '251.209.117.218', None, '5 Mallory Road', 'New York City', 'NY', '10009', 40.7262, -73.9796, datetime.datetime(2017, 4, 26, 0, 0), 'thank-you party'),
 (15883, None, 'Abey', 'Tapping', None, 'atappingc96@shinystat.com', 'M', '18.67.193.104', None, '80 Kedzie Drive', 'New York City', 'NY', '10045', 40.7086, -74.0087, datetime.datetime(2020, 6, 5, 0, 0), 'thank-you party'),
 (15907, None, 'Shaughn', 'Suckling', None, 'ssucklingc9u@pinterest.com', 'M', '157.85.97.45', '718-829-3123', '59 Carey Park', 'New York City', 'NY', '10004', 40.6964, -74.0253, datetime.datetime(2018, 11, 1, 0, 0), 'thank-you party'),
 (19303, None, 'Sheffield', 'Jowle', None, 'sjowleew6@ftc.gov', 'M', '115.22.37.60', '212-179-2827', '5682 1st Trail', 'New York City', 'NY', '10160', 40.7808, -73.9772, datetime.datetime(2013, 11, 18, 0, 0), 'thank-you party'),
 (21786, None, 'Morton', 'Wantling', None, 'mwantlinggt5@mozilla.com', 'M', '29.247.44.180', '212-323-3585', '798 Reinke Hill', 'New York City', 'NY', '10034', 40.8662, -73.9221, datetime.datetime(2016, 11, 6, 0, 0), 'thank-you party'),
 (21806, None, 'Erin', 'Praton', None, 'epratongtp@cbsnews.com', 'F', '245.131.141.68', '646-912-4809', '51497 Crowley Junction', 'New York City', 'NY', '10004', 40.6964, -74.0253, datetime.datetime(2019, 1, 18, 0, 0), 'thank-you party'),
 (25415, None, 'Dorry', 'McGinnell', None, 'dmcginnelljly@amazon.com', 'F', '223.150.30.48', '212-229-7637', '77235 Knutson Alley', 'New York City', 'NY', '10270', 40.7069, -74.0082, datetime.datetime(2013, 4, 13, 0, 0), 'thank-you party'),
 (28871, None, 'Hyacinthie', 'McElhargy', None, 'hmcelhargym9y@over-blog.com', 'F', '121.79.224.219', '212-903-9718', '18 Stang Way', 'New York City', 'NY', '10009', 40.7262, -73.9796, datetime.datetime(2019, 3, 22, 0, 0), 'thank-you party'),
 (28891, None, 'Cherlyn', 'Wooddisse', None, 'cwooddissemai@ebay.com', 'F', '185.105.0.101', None, '241 Doe Crossing Avenue', 'New York City', 'NY', '10165', 40.7524, -73.9791, datetime.datetime(2019, 3, 21, 0, 0), 'thank-you party'),
 (29029, None, 'Andrey', 'Sussex', None, 'asussexmec@sphinn.com', 'M', '80.249.54.139', '212-242-5881', '15727 Emmet Point', 'New York City', 'NY', '10260', 40.7808, -73.9772, datetime.datetime(2016, 7, 25, 0, 0), 'thank-you party'),
 (29197, None, 'Sherwood', 'Gorcke', None, 'sgorckemj0@icq.com', 'M', '210.226.203.39', '646-756-5931', '9 Rockefeller Way', 'New York City', 'NY', '10060', 40.7808, -73.9772, datetime.datetime(2019, 9, 9, 0, 0), 'thank-you party'),
 (32109, None, 'Sherrie'

8. Elimina la tabla customers_nyc según lo solicitado por el gerente usando DROP TABLE:

In [ ]:
%%sql
   DROP TABLE customers_nyc;

 * postgresql://postgres:***@localhost:5432/sqlda
Done.


[]


Esto eliminará la tabla customers_nyc de la base de datos.

# 1.10 SQL y Análisis de Datos

A lo largo de este capítulo, habrás observado que los términos "tabla SQL" y "conjunto de datos" se usan de manera casi sinónima. De hecho, podemos ver a las tablas SQL como conjuntos de datos, donde las filas representan unidades individuales de observación y las columnas actúan como características o atributos. Al percibir las tablas SQL bajo esta óptica, es evidente que SQL es una herramienta óptima para gestionar y almacenar datos en un ordenador.

No obstante, el alcance de SQL va más allá de ser un simple almacén de datos. Las implementaciones actuales de SQL no solo facilitan el almacenamiento, sino que también ofrecen herramientas avanzadas para procesar y analizar datos mediante diversas funciones. Con SQL, es posible depurar datos, reformularlos en estructuras más adecuadas y llevar a cabo análisis estadísticos para identificar patrones reveladores. El propósito subsiguiente de este libro es profundizar en cómo se puede emplear SQL de manera eficaz y eficiente para estos fines.

# Resumen
- **Bases de datos relacionales**: Estas son esenciales para la analítica de datos, ofreciendo una tecnología madura y omnipresente para almacenar y consultar datos estructurados.
  
- **Tablas**: Las bases de datos relacionales almacenan datos en forma de tablas, lo que ofrece rendimiento, eficiencia y facilidad de uso.

- **Lenguaje SQL**: Es el lenguaje estándar para acceder y manipular bases de datos relacionales. Admite una amplia variedad de tipos de datos.

- **Operaciones CRUD**: Con SQL, puedes Crear, Leer, Actualizar y Eliminar (CRUD) datos. Esto incluye crear y eliminar tablas, insertar, actualizar y eliminar registros.

- **Consulta y filtrado**: SQL permite al usuario seleccionar campos específicos, filtrar datos y ordenarlos según sus necesidades.

Próximos pasos. Después de entender los fundamentos de SQL, el siguiente enfoque es cómo se puede usar SQL para la limpieza y transformación de datos en la analítica.
